// Code generated by ent, DO NOT EDIT.

package ingestionjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldProjectID, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldSourceID, v))
}

// ProgressPercent applies equality check predicate on the "progress_percent" field. It's identical to ProgressPercentEQ.
func ProgressPercent(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldProgressPercent, v))
}

// ProcessedFiles applies equality check predicate on the "processed_files" field. It's identical to ProcessedFilesEQ.
func ProcessedFiles(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldProcessedFiles, v))
}

// TotalFiles applies equality check predicate on the "total_files" field. It's identical to TotalFilesEQ.
func TotalFiles(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldTotalFiles, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldFinishedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldProjectID, vs...))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...uuid.UUID) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldSourceID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldStatus, vs...))
}

// ProgressPercentEQ applies the EQ predicate on the "progress_percent" field.
func ProgressPercentEQ(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldProgressPercent, v))
}

// ProgressPercentNEQ applies the NEQ predicate on the "progress_percent" field.
func ProgressPercentNEQ(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldProgressPercent, v))
}

// ProgressPercentIn applies the In predicate on the "progress_percent" field.
func ProgressPercentIn(vs ...int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldProgressPercent, vs...))
}

// ProgressPercentNotIn applies the NotIn predicate on the "progress_percent" field.
func ProgressPercentNotIn(vs ...int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldProgressPercent, vs...))
}

// ProgressPercentGT applies the GT predicate on the "progress_percent" field.
func ProgressPercentGT(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGT(FieldProgressPercent, v))
}

// ProgressPercentGTE applies the GTE predicate on the "progress_percent" field.
func ProgressPercentGTE(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGTE(FieldProgressPercent, v))
}

// ProgressPercentLT applies the LT predicate on the "progress_percent" field.
func ProgressPercentLT(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLT(FieldProgressPercent, v))
}

// ProgressPercentLTE applies the LTE predicate on the "progress_percent" field.
func ProgressPercentLTE(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLTE(FieldProgressPercent, v))
}

// ProcessedFilesEQ applies the EQ predicate on the "processed_files" field.
func ProcessedFilesEQ(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldProcessedFiles, v))
}

// ProcessedFilesNEQ applies the NEQ predicate on the "processed_files" field.
func ProcessedFilesNEQ(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldProcessedFiles, v))
}

// ProcessedFilesIn applies the In predicate on the "processed_files" field.
func ProcessedFilesIn(vs ...int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldProcessedFiles, vs...))
}

// ProcessedFilesNotIn applies the NotIn predicate on the "processed_files" field.
func ProcessedFilesNotIn(vs ...int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldProcessedFiles, vs...))
}

// ProcessedFilesGT applies the GT predicate on the "processed_files" field.
func ProcessedFilesGT(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGT(FieldProcessedFiles, v))
}

// ProcessedFilesGTE applies the GTE predicate on the "processed_files" field.
func ProcessedFilesGTE(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGTE(FieldProcessedFiles, v))
}

// ProcessedFilesLT applies the LT predicate on the "processed_files" field.
func ProcessedFilesLT(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLT(FieldProcessedFiles, v))
}

// ProcessedFilesLTE applies the LTE predicate on the "processed_files" field.
func ProcessedFilesLTE(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLTE(FieldProcessedFiles, v))
}

// TotalFilesEQ applies the EQ predicate on the "total_files" field.
func TotalFilesEQ(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldTotalFiles, v))
}

// TotalFilesNEQ applies the NEQ predicate on the "total_files" field.
func TotalFilesNEQ(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldTotalFiles, v))
}

// TotalFilesIn applies the In predicate on the "total_files" field.
func TotalFilesIn(vs ...int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldTotalFiles, vs...))
}

// TotalFilesNotIn applies the NotIn predicate on the "total_files" field.
func TotalFilesNotIn(vs ...int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldTotalFiles, vs...))
}

// TotalFilesGT applies the GT predicate on the "total_files" field.
func TotalFilesGT(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGT(FieldTotalFiles, v))
}

// TotalFilesGTE applies the GTE predicate on the "total_files" field.
func TotalFilesGTE(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGTE(FieldTotalFiles, v))
}

// TotalFilesLT applies the LT predicate on the "total_files" field.
func TotalFilesLT(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLT(FieldTotalFiles, v))
}

// TotalFilesLTE applies the LTE predicate on the "total_files" field.
func TotalFilesLTE(v int) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLTE(FieldTotalFiles, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.IngestionJob {
	return predicate.IngestionJob(sql.FieldNotNull(FieldFinishedAt))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.IngestionJob {
	return predicate.IngestionJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.IngestionJob {
	return predicate.IngestionJob(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSource applies the HasEdge predicate on the "source" edge.
func HasSource() predicate.IngestionJob {
	return predicate.IngestionJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceTable, SourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceWith applies the HasEdge predicate on the "source" edge with a given conditions (other predicates).
func HasSourceWith(preds ...predicate.Source) predicate.IngestionJob {
	return predicate.IngestionJob(func(s *sql.Selector) {
		step := newSourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IngestionJob) predicate.IngestionJob {
	return predicate.IngestionJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IngestionJob) predicate.IngestionJob {
	return predicate.IngestionJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IngestionJob) predicate.IngestionJob {
	return predicate.IngestionJob(sql.NotPredicates(p))
}
