// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/auditlog"
	"github.com/your-org/contextforge/internal/ent/predicate"
	"github.com/your-org/contextforge/internal/ent/project"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *AuditLogUpdate) SetProjectID(v uuid.UUID) *AuditLogUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableProjectID(v *uuid.UUID) *AuditLogUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuditLogUpdate) SetUserID(v uuid.UUID) *AuditLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableUserID(v *uuid.UUID) *AuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v string) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *AuditLogUpdate) SetResourceType(v string) *AuditLogUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResourceType(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *AuditLogUpdate) SetResourceID(v string) *AuditLogUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResourceID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *AuditLogUpdate) SetDetails(v string) *AuditLogUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableDetails(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *AuditLogUpdate) ClearDetails() *AuditLogUpdate {
	_u.mutation.ClearDetails()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *AuditLogUpdate) SetIPAddress(v string) *AuditLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableIPAddress(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *AuditLogUpdate) ClearIPAddress() *AuditLogUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *AuditLogUpdate) SetProject(v *Project) *AuditLogUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *AuditLogUpdate) ClearProject() *AuditLogUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := auditlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := auditlog.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_id": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuditLog.project"`)
	}
	return nil
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(auditlog.FieldDetails, field.TypeString, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(auditlog.FieldDetails, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ProjectTable,
			Columns: []string{auditlog.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ProjectTable,
			Columns: []string{auditlog.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetProjectID sets the "project_id" field.
func (_u *AuditLogUpdateOne) SetProjectID(v uuid.UUID) *AuditLogUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableProjectID(v *uuid.UUID) *AuditLogUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuditLogUpdateOne) SetUserID(v uuid.UUID) *AuditLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableUserID(v *uuid.UUID) *AuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v string) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *AuditLogUpdateOne) SetResourceType(v string) *AuditLogUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResourceType(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *AuditLogUpdateOne) SetResourceID(v string) *AuditLogUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResourceID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *AuditLogUpdateOne) SetDetails(v string) *AuditLogUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableDetails(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *AuditLogUpdateOne) ClearDetails() *AuditLogUpdateOne {
	_u.mutation.ClearDetails()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *AuditLogUpdateOne) SetIPAddress(v string) *AuditLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableIPAddress(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *AuditLogUpdateOne) ClearIPAddress() *AuditLogUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *AuditLogUpdateOne) SetProject(v *Project) *AuditLogUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *AuditLogUpdateOne) ClearProject() *AuditLogUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := auditlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := auditlog.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_id": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuditLog.project"`)
	}
	return nil
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(auditlog.FieldDetails, field.TypeString, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(auditlog.FieldDetails, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ProjectTable,
			Columns: []string{auditlog.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ProjectTable,
			Columns: []string{auditlog.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
