// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/chatmessage"
	"github.com/your-org/contextforge/internal/ent/conversation"
	"github.com/your-org/contextforge/internal/ent/predicate"
	"github.com/your-org/contextforge/internal/model"
)

// ChatMessageUpdate is the builder for updating ChatMessage entities.
type ChatMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMessageMutation
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdate) Where(ps ...predicate.ChatMessage) *ChatMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ChatMessageUpdate) SetConversationID(v uuid.UUID) *ChatMessageUpdate {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableConversationID(v *uuid.UUID) *ChatMessageUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ChatMessageUpdate) SetRole(v string) *ChatMessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableRole(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ChatMessageUpdate) SetContent(v string) *ChatMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableContent(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetCitations sets the "citations" field.
func (_u *ChatMessageUpdate) SetCitations(v []model.Citation) *ChatMessageUpdate {
	_u.mutation.SetCitations(v)
	return _u
}

// AppendCitations appends value to the "citations" field.
func (_u *ChatMessageUpdate) AppendCitations(v []model.Citation) *ChatMessageUpdate {
	_u.mutation.AppendCitations(v)
	return _u
}

// ClearCitations clears the value of the "citations" field.
func (_u *ChatMessageUpdate) ClearCitations() *ChatMessageUpdate {
	_u.mutation.ClearCitations()
	return _u
}

// SetTokensUsed sets the "tokens_used" field.
func (_u *ChatMessageUpdate) SetTokensUsed(v int) *ChatMessageUpdate {
	_u.mutation.ResetTokensUsed()
	_u.mutation.SetTokensUsed(v)
	return _u
}

// SetNillableTokensUsed sets the "tokens_used" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableTokensUsed(v *int) *ChatMessageUpdate {
	if v != nil {
		_u.SetTokensUsed(*v)
	}
	return _u
}

// AddTokensUsed adds value to the "tokens_used" field.
func (_u *ChatMessageUpdate) AddTokensUsed(v int) *ChatMessageUpdate {
	_u.mutation.AddTokensUsed(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *ChatMessageUpdate) SetDurationMs(v int64) *ChatMessageUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableDurationMs(v *int64) *ChatMessageUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *ChatMessageUpdate) AddDurationMs(v int64) *ChatMessageUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *ChatMessageUpdate) SetConversation(v *Conversation) *ChatMessageUpdate {
	return _u.SetConversationID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdate) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *ChatMessageUpdate) ClearConversation() *ChatMessageUpdate {
	_u.mutation.ClearConversation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := chatmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.role": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessage.conversation"`)
	}
	return nil
}

func (_u *ChatMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(chatmessage.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Citations(); ok {
		_spec.SetField(chatmessage.FieldCitations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCitations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, chatmessage.FieldCitations, value)
		})
	}
	if _u.mutation.CitationsCleared() {
		_spec.ClearField(chatmessage.FieldCitations, field.TypeJSON)
	}
	if value, ok := _u.mutation.TokensUsed(); ok {
		_spec.SetField(chatmessage.FieldTokensUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokensUsed(); ok {
		_spec.AddField(chatmessage.FieldTokensUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(chatmessage.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(chatmessage.FieldDurationMs, field.TypeInt64, value)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatMessageUpdateOne is the builder for updating a single ChatMessage entity.
type ChatMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMessageMutation
}

// SetConversationID sets the "conversation_id" field.
func (_u *ChatMessageUpdateOne) SetConversationID(v uuid.UUID) *ChatMessageUpdateOne {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableConversationID(v *uuid.UUID) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ChatMessageUpdateOne) SetRole(v string) *ChatMessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableRole(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ChatMessageUpdateOne) SetContent(v string) *ChatMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableContent(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetCitations sets the "citations" field.
func (_u *ChatMessageUpdateOne) SetCitations(v []model.Citation) *ChatMessageUpdateOne {
	_u.mutation.SetCitations(v)
	return _u
}

// AppendCitations appends value to the "citations" field.
func (_u *ChatMessageUpdateOne) AppendCitations(v []model.Citation) *ChatMessageUpdateOne {
	_u.mutation.AppendCitations(v)
	return _u
}

// ClearCitations clears the value of the "citations" field.
func (_u *ChatMessageUpdateOne) ClearCitations() *ChatMessageUpdateOne {
	_u.mutation.ClearCitations()
	return _u
}

// SetTokensUsed sets the "tokens_used" field.
func (_u *ChatMessageUpdateOne) SetTokensUsed(v int) *ChatMessageUpdateOne {
	_u.mutation.ResetTokensUsed()
	_u.mutation.SetTokensUsed(v)
	return _u
}

// SetNillableTokensUsed sets the "tokens_used" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableTokensUsed(v *int) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetTokensUsed(*v)
	}
	return _u
}

// AddTokensUsed adds value to the "tokens_used" field.
func (_u *ChatMessageUpdateOne) AddTokensUsed(v int) *ChatMessageUpdateOne {
	_u.mutation.AddTokensUsed(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *ChatMessageUpdateOne) SetDurationMs(v int64) *ChatMessageUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableDurationMs(v *int64) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *ChatMessageUpdateOne) AddDurationMs(v int64) *ChatMessageUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *ChatMessageUpdateOne) SetConversation(v *Conversation) *ChatMessageUpdateOne {
	return _u.SetConversationID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdateOne) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *ChatMessageUpdateOne) ClearConversation() *ChatMessageUpdateOne {
	_u.mutation.ClearConversation()
	return _u
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdateOne) Where(ps ...predicate.ChatMessage) *ChatMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatMessageUpdateOne) Select(field string, fields ...string) *ChatMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatMessage entity.
func (_u *ChatMessageUpdateOne) Save(ctx context.Context) (*ChatMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) SaveX(ctx context.Context) *ChatMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := chatmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.role": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessage.conversation"`)
	}
	return nil
}

func (_u *ChatMessageUpdateOne) sqlSave(ctx context.Context) (_node *ChatMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatmessage.FieldID)
		for _, f := range fields {
			if !chatmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(chatmessage.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Citations(); ok {
		_spec.SetField(chatmessage.FieldCitations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCitations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, chatmessage.FieldCitations, value)
		})
	}
	if _u.mutation.CitationsCleared() {
		_spec.ClearField(chatmessage.FieldCitations, field.TypeJSON)
	}
	if value, ok := _u.mutation.TokensUsed(); ok {
		_spec.SetField(chatmessage.FieldTokensUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokensUsed(); ok {
		_spec.AddField(chatmessage.FieldTokensUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(chatmessage.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(chatmessage.FieldDurationMs, field.TypeInt64, value)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
