// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/databasesource"
	"github.com/your-org/contextforge/internal/ent/predicate"
	"github.com/your-org/contextforge/internal/ent/project"
	"github.com/your-org/contextforge/internal/ent/source"
)

// DatabaseSourceQuery is the builder for querying DatabaseSource entities.
type DatabaseSourceQuery struct {
	config
	ctx         *QueryContext
	order       []databasesource.OrderOption
	inters      []Interceptor
	predicates  []predicate.DatabaseSource
	withSource  *SourceQuery
	withProject *ProjectQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DatabaseSourceQuery builder.
func (_q *DatabaseSourceQuery) Where(ps ...predicate.DatabaseSource) *DatabaseSourceQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DatabaseSourceQuery) Limit(limit int) *DatabaseSourceQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DatabaseSourceQuery) Offset(offset int) *DatabaseSourceQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DatabaseSourceQuery) Unique(unique bool) *DatabaseSourceQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DatabaseSourceQuery) Order(o ...databasesource.OrderOption) *DatabaseSourceQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySource chains the current query on the "source" edge.
func (_q *DatabaseSourceQuery) QuerySource() *SourceQuery {
	query := (&SourceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(databasesource.Table, databasesource.FieldID, selector),
			sqlgraph.To(source.Table, source.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, databasesource.SourceTable, databasesource.SourceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProject chains the current query on the "project" edge.
func (_q *DatabaseSourceQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(databasesource.Table, databasesource.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, databasesource.ProjectTable, databasesource.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DatabaseSource entity from the query.
// Returns a *NotFoundError when no DatabaseSource was found.
func (_q *DatabaseSourceQuery) First(ctx context.Context) (*DatabaseSource, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{databasesource.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DatabaseSourceQuery) FirstX(ctx context.Context) *DatabaseSource {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DatabaseSource ID from the query.
// Returns a *NotFoundError when no DatabaseSource ID was found.
func (_q *DatabaseSourceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{databasesource.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DatabaseSourceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DatabaseSource entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DatabaseSource entity is found.
// Returns a *NotFoundError when no DatabaseSource entities are found.
func (_q *DatabaseSourceQuery) Only(ctx context.Context) (*DatabaseSource, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{databasesource.Label}
	default:
		return nil, &NotSingularError{databasesource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DatabaseSourceQuery) OnlyX(ctx context.Context) *DatabaseSource {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DatabaseSource ID in the query.
// Returns a *NotSingularError when more than one DatabaseSource ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DatabaseSourceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{databasesource.Label}
	default:
		err = &NotSingularError{databasesource.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DatabaseSourceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DatabaseSources.
func (_q *DatabaseSourceQuery) All(ctx context.Context) ([]*DatabaseSource, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DatabaseSource, *DatabaseSourceQuery]()
	return withInterceptors[[]*DatabaseSource](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DatabaseSourceQuery) AllX(ctx context.Context) []*DatabaseSource {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DatabaseSource IDs.
func (_q *DatabaseSourceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(databasesource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DatabaseSourceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DatabaseSourceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DatabaseSourceQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DatabaseSourceQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DatabaseSourceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DatabaseSourceQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DatabaseSourceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DatabaseSourceQuery) Clone() *DatabaseSourceQuery {
	if _q == nil {
		return nil
	}
	return &DatabaseSourceQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]databasesource.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.DatabaseSource{}, _q.predicates...),
		withSource:  _q.withSource.Clone(),
		withProject: _q.withProject.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSource tells the query-builder to eager-load the nodes that are connected to
// the "source" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DatabaseSourceQuery) WithSource(opts ...func(*SourceQuery)) *DatabaseSourceQuery {
	query := (&SourceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSource = query
	return _q
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DatabaseSourceQuery) WithProject(opts ...func(*ProjectQuery)) *DatabaseSourceQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SourceID uuid.UUID `json:"source_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DatabaseSource.Query().
//		GroupBy(databasesource.FieldSourceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DatabaseSourceQuery) GroupBy(field string, fields ...string) *DatabaseSourceGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DatabaseSourceGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = databasesource.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SourceID uuid.UUID `json:"source_id,omitempty"`
//	}
//
//	client.DatabaseSource.Query().
//		Select(databasesource.FieldSourceID).
//		Scan(ctx, &v)
func (_q *DatabaseSourceQuery) Select(fields ...string) *DatabaseSourceSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DatabaseSourceSelect{DatabaseSourceQuery: _q}
	sbuild.label = databasesource.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DatabaseSourceSelect configured with the given aggregations.
func (_q *DatabaseSourceQuery) Aggregate(fns ...AggregateFunc) *DatabaseSourceSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DatabaseSourceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !databasesource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DatabaseSourceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DatabaseSource, error) {
	var (
		nodes       = []*DatabaseSource{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withSource != nil,
			_q.withProject != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DatabaseSource).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DatabaseSource{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSource; query != nil {
		if err := _q.loadSource(ctx, query, nodes, nil,
			func(n *DatabaseSource, e *Source) { n.Edges.Source = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *DatabaseSource, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DatabaseSourceQuery) loadSource(ctx context.Context, query *SourceQuery, nodes []*DatabaseSource, init func(*DatabaseSource), assign func(*DatabaseSource, *Source)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DatabaseSource)
	for i := range nodes {
		fk := nodes[i].SourceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(source.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "source_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DatabaseSourceQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*DatabaseSource, init func(*DatabaseSource), assign func(*DatabaseSource, *Project)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DatabaseSource)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DatabaseSourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DatabaseSourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(databasesource.Table, databasesource.Columns, sqlgraph.NewFieldSpec(databasesource.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, databasesource.FieldID)
		for i := range fields {
			if fields[i] != databasesource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSource != nil {
			_spec.Node.AddColumnOnce(databasesource.FieldSourceID)
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(databasesource.FieldProjectID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DatabaseSourceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(databasesource.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = databasesource.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DatabaseSourceGroupBy is the group-by builder for DatabaseSource entities.
type DatabaseSourceGroupBy struct {
	selector
	build *DatabaseSourceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DatabaseSourceGroupBy) Aggregate(fns ...AggregateFunc) *DatabaseSourceGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DatabaseSourceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DatabaseSourceQuery, *DatabaseSourceGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DatabaseSourceGroupBy) sqlScan(ctx context.Context, root *DatabaseSourceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DatabaseSourceSelect is the builder for selecting fields of DatabaseSource entities.
type DatabaseSourceSelect struct {
	*DatabaseSourceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DatabaseSourceSelect) Aggregate(fns ...AggregateFunc) *DatabaseSourceSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DatabaseSourceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DatabaseSourceQuery, *DatabaseSourceSelect](ctx, _s.DatabaseSourceQuery, _s, _s.inters, v)
}

func (_s *DatabaseSourceSelect) sqlScan(ctx context.Context, root *DatabaseSourceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
