// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/document"
	"github.com/your-org/contextforge/internal/ent/documentchunk"
	"github.com/your-org/contextforge/internal/ent/predicate"
	"github.com/your-org/contextforge/internal/ent/project"
)

// DocumentChunkUpdate is the builder for updating DocumentChunk entities.
type DocumentChunkUpdate struct {
	config
	hooks    []Hook
	mutation *DocumentChunkMutation
}

// Where appends a list predicates to the DocumentChunkUpdate builder.
func (_u *DocumentChunkUpdate) Where(ps ...predicate.DocumentChunk) *DocumentChunkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *DocumentChunkUpdate) SetProjectID(v uuid.UUID) *DocumentChunkUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableProjectID(v *uuid.UUID) *DocumentChunkUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *DocumentChunkUpdate) SetDocumentID(v uuid.UUID) *DocumentChunkUpdate {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableDocumentID(v *uuid.UUID) *DocumentChunkUpdate {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetChunkIndex sets the "chunk_index" field.
func (_u *DocumentChunkUpdate) SetChunkIndex(v int) *DocumentChunkUpdate {
	_u.mutation.ResetChunkIndex()
	_u.mutation.SetChunkIndex(v)
	return _u
}

// SetNillableChunkIndex sets the "chunk_index" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableChunkIndex(v *int) *DocumentChunkUpdate {
	if v != nil {
		_u.SetChunkIndex(*v)
	}
	return _u
}

// AddChunkIndex adds value to the "chunk_index" field.
func (_u *DocumentChunkUpdate) AddChunkIndex(v int) *DocumentChunkUpdate {
	_u.mutation.AddChunkIndex(v)
	return _u
}

// SetStartLine sets the "start_line" field.
func (_u *DocumentChunkUpdate) SetStartLine(v int) *DocumentChunkUpdate {
	_u.mutation.ResetStartLine()
	_u.mutation.SetStartLine(v)
	return _u
}

// SetNillableStartLine sets the "start_line" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableStartLine(v *int) *DocumentChunkUpdate {
	if v != nil {
		_u.SetStartLine(*v)
	}
	return _u
}

// AddStartLine adds value to the "start_line" field.
func (_u *DocumentChunkUpdate) AddStartLine(v int) *DocumentChunkUpdate {
	_u.mutation.AddStartLine(v)
	return _u
}

// SetEndLine sets the "end_line" field.
func (_u *DocumentChunkUpdate) SetEndLine(v int) *DocumentChunkUpdate {
	_u.mutation.ResetEndLine()
	_u.mutation.SetEndLine(v)
	return _u
}

// SetNillableEndLine sets the "end_line" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableEndLine(v *int) *DocumentChunkUpdate {
	if v != nil {
		_u.SetEndLine(*v)
	}
	return _u
}

// AddEndLine adds value to the "end_line" field.
func (_u *DocumentChunkUpdate) AddEndLine(v int) *DocumentChunkUpdate {
	_u.mutation.AddEndLine(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *DocumentChunkUpdate) SetContent(v string) *DocumentChunkUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableContent(v *string) *DocumentChunkUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *DocumentChunkUpdate) SetContentHash(v string) *DocumentChunkUpdate {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableContentHash(v *string) *DocumentChunkUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetTokenCount sets the "token_count" field.
func (_u *DocumentChunkUpdate) SetTokenCount(v int) *DocumentChunkUpdate {
	_u.mutation.ResetTokenCount()
	_u.mutation.SetTokenCount(v)
	return _u
}

// SetNillableTokenCount sets the "token_count" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableTokenCount(v *int) *DocumentChunkUpdate {
	if v != nil {
		_u.SetTokenCount(*v)
	}
	return _u
}

// AddTokenCount adds value to the "token_count" field.
func (_u *DocumentChunkUpdate) AddTokenCount(v int) *DocumentChunkUpdate {
	_u.mutation.AddTokenCount(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *DocumentChunkUpdate) SetProject(v *Project) *DocumentChunkUpdate {
	return _u.SetProjectID(v.ID)
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentChunkUpdate) SetDocument(v *Document) *DocumentChunkUpdate {
	return _u.SetDocumentID(v.ID)
}

// Mutation returns the DocumentChunkMutation object of the builder.
func (_u *DocumentChunkUpdate) Mutation() *DocumentChunkMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *DocumentChunkUpdate) ClearProject() *DocumentChunkUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentChunkUpdate) ClearDocument() *DocumentChunkUpdate {
	_u.mutation.ClearDocument()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentChunkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentChunkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentChunkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentChunkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentChunkUpdate) check() error {
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := documentchunk.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "DocumentChunk.content_hash": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentChunk.project"`)
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentChunk.document"`)
	}
	return nil
}

func (_u *DocumentChunkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentchunk.Table, documentchunk.Columns, sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChunkIndex(); ok {
		_spec.SetField(documentchunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkIndex(); ok {
		_spec.AddField(documentchunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartLine(); ok {
		_spec.SetField(documentchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartLine(); ok {
		_spec.AddField(documentchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndLine(); ok {
		_spec.SetField(documentchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndLine(); ok {
		_spec.AddField(documentchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(documentchunk.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(documentchunk.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenCount(); ok {
		_spec.SetField(documentchunk.FieldTokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenCount(); ok {
		_spec.AddField(documentchunk.FieldTokenCount, field.TypeInt, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.ProjectTable,
			Columns: []string{documentchunk.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.ProjectTable,
			Columns: []string{documentchunk.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.DocumentTable,
			Columns: []string{documentchunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.DocumentTable,
			Columns: []string{documentchunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentchunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentChunkUpdateOne is the builder for updating a single DocumentChunk entity.
type DocumentChunkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DocumentChunkMutation
}

// SetProjectID sets the "project_id" field.
func (_u *DocumentChunkUpdateOne) SetProjectID(v uuid.UUID) *DocumentChunkUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableProjectID(v *uuid.UUID) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *DocumentChunkUpdateOne) SetDocumentID(v uuid.UUID) *DocumentChunkUpdateOne {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableDocumentID(v *uuid.UUID) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetChunkIndex sets the "chunk_index" field.
func (_u *DocumentChunkUpdateOne) SetChunkIndex(v int) *DocumentChunkUpdateOne {
	_u.mutation.ResetChunkIndex()
	_u.mutation.SetChunkIndex(v)
	return _u
}

// SetNillableChunkIndex sets the "chunk_index" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableChunkIndex(v *int) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetChunkIndex(*v)
	}
	return _u
}

// AddChunkIndex adds value to the "chunk_index" field.
func (_u *DocumentChunkUpdateOne) AddChunkIndex(v int) *DocumentChunkUpdateOne {
	_u.mutation.AddChunkIndex(v)
	return _u
}

// SetStartLine sets the "start_line" field.
func (_u *DocumentChunkUpdateOne) SetStartLine(v int) *DocumentChunkUpdateOne {
	_u.mutation.ResetStartLine()
	_u.mutation.SetStartLine(v)
	return _u
}

// SetNillableStartLine sets the "start_line" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableStartLine(v *int) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetStartLine(*v)
	}
	return _u
}

// AddStartLine adds value to the "start_line" field.
func (_u *DocumentChunkUpdateOne) AddStartLine(v int) *DocumentChunkUpdateOne {
	_u.mutation.AddStartLine(v)
	return _u
}

// SetEndLine sets the "end_line" field.
func (_u *DocumentChunkUpdateOne) SetEndLine(v int) *DocumentChunkUpdateOne {
	_u.mutation.ResetEndLine()
	_u.mutation.SetEndLine(v)
	return _u
}

// SetNillableEndLine sets the "end_line" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableEndLine(v *int) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetEndLine(*v)
	}
	return _u
}

// AddEndLine adds value to the "end_line" field.
func (_u *DocumentChunkUpdateOne) AddEndLine(v int) *DocumentChunkUpdateOne {
	_u.mutation.AddEndLine(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *DocumentChunkUpdateOne) SetContent(v string) *DocumentChunkUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableContent(v *string) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *DocumentChunkUpdateOne) SetContentHash(v string) *DocumentChunkUpdateOne {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableContentHash(v *string) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetTokenCount sets the "token_count" field.
func (_u *DocumentChunkUpdateOne) SetTokenCount(v int) *DocumentChunkUpdateOne {
	_u.mutation.ResetTokenCount()
	_u.mutation.SetTokenCount(v)
	return _u
}

// SetNillableTokenCount sets the "token_count" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableTokenCount(v *int) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetTokenCount(*v)
	}
	return _u
}

// AddTokenCount adds value to the "token_count" field.
func (_u *DocumentChunkUpdateOne) AddTokenCount(v int) *DocumentChunkUpdateOne {
	_u.mutation.AddTokenCount(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *DocumentChunkUpdateOne) SetProject(v *Project) *DocumentChunkUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentChunkUpdateOne) SetDocument(v *Document) *DocumentChunkUpdateOne {
	return _u.SetDocumentID(v.ID)
}

// Mutation returns the DocumentChunkMutation object of the builder.
func (_u *DocumentChunkUpdateOne) Mutation() *DocumentChunkMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *DocumentChunkUpdateOne) ClearProject() *DocumentChunkUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentChunkUpdateOne) ClearDocument() *DocumentChunkUpdateOne {
	_u.mutation.ClearDocument()
	return _u
}

// Where appends a list predicates to the DocumentChunkUpdate builder.
func (_u *DocumentChunkUpdateOne) Where(ps ...predicate.DocumentChunk) *DocumentChunkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentChunkUpdateOne) Select(field string, fields ...string) *DocumentChunkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DocumentChunk entity.
func (_u *DocumentChunkUpdateOne) Save(ctx context.Context) (*DocumentChunk, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentChunkUpdateOne) SaveX(ctx context.Context) *DocumentChunk {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentChunkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentChunkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentChunkUpdateOne) check() error {
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := documentchunk.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "DocumentChunk.content_hash": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentChunk.project"`)
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentChunk.document"`)
	}
	return nil
}

func (_u *DocumentChunkUpdateOne) sqlSave(ctx context.Context) (_node *DocumentChunk, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentchunk.Table, documentchunk.Columns, sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DocumentChunk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, documentchunk.FieldID)
		for _, f := range fields {
			if !documentchunk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != documentchunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChunkIndex(); ok {
		_spec.SetField(documentchunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkIndex(); ok {
		_spec.AddField(documentchunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartLine(); ok {
		_spec.SetField(documentchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartLine(); ok {
		_spec.AddField(documentchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndLine(); ok {
		_spec.SetField(documentchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndLine(); ok {
		_spec.AddField(documentchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(documentchunk.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(documentchunk.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenCount(); ok {
		_spec.SetField(documentchunk.FieldTokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenCount(); ok {
		_spec.AddField(documentchunk.FieldTokenCount, field.TypeInt, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.ProjectTable,
			Columns: []string{documentchunk.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.ProjectTable,
			Columns: []string{documentchunk.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.DocumentTable,
			Columns: []string{documentchunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.DocumentTable,
			Columns: []string{documentchunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DocumentChunk{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentchunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
