// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/your-org/contextforge/internal/ent/ingestionjob"
	"github.com/your-org/contextforge/internal/ent/predicate"
)

// IngestionJobDelete is the builder for deleting a IngestionJob entity.
type IngestionJobDelete struct {
	config
	hooks    []Hook
	mutation *IngestionJobMutation
}

// Where appends a list predicates to the IngestionJobDelete builder.
func (_d *IngestionJobDelete) Where(ps ...predicate.IngestionJob) *IngestionJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *IngestionJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IngestionJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *IngestionJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ingestionjob.Table, sqlgraph.NewFieldSpec(ingestionjob.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// IngestionJobDeleteOne is the builder for deleting a single IngestionJob entity.
type IngestionJobDeleteOne struct {
	_d *IngestionJobDelete
}

// Where appends a list predicates to the IngestionJobDelete builder.
func (_d *IngestionJobDeleteOne) Where(ps ...predicate.IngestionJob) *IngestionJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *IngestionJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ingestionjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IngestionJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
