// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/ingestionjob"
	"github.com/your-org/contextforge/internal/ent/predicate"
	"github.com/your-org/contextforge/internal/ent/project"
	"github.com/your-org/contextforge/internal/ent/source"
)

// IngestionJobUpdate is the builder for updating IngestionJob entities.
type IngestionJobUpdate struct {
	config
	hooks    []Hook
	mutation *IngestionJobMutation
}

// Where appends a list predicates to the IngestionJobUpdate builder.
func (_u *IngestionJobUpdate) Where(ps ...predicate.IngestionJob) *IngestionJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *IngestionJobUpdate) SetProjectID(v uuid.UUID) *IngestionJobUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *IngestionJobUpdate) SetNillableProjectID(v *uuid.UUID) *IngestionJobUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *IngestionJobUpdate) SetSourceID(v uuid.UUID) *IngestionJobUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *IngestionJobUpdate) SetNillableSourceID(v *uuid.UUID) *IngestionJobUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IngestionJobUpdate) SetStatus(v ingestionjob.Status) *IngestionJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IngestionJobUpdate) SetNillableStatus(v *ingestionjob.Status) *IngestionJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgressPercent sets the "progress_percent" field.
func (_u *IngestionJobUpdate) SetProgressPercent(v int) *IngestionJobUpdate {
	_u.mutation.ResetProgressPercent()
	_u.mutation.SetProgressPercent(v)
	return _u
}

// SetNillableProgressPercent sets the "progress_percent" field if the given value is not nil.
func (_u *IngestionJobUpdate) SetNillableProgressPercent(v *int) *IngestionJobUpdate {
	if v != nil {
		_u.SetProgressPercent(*v)
	}
	return _u
}

// AddProgressPercent adds value to the "progress_percent" field.
func (_u *IngestionJobUpdate) AddProgressPercent(v int) *IngestionJobUpdate {
	_u.mutation.AddProgressPercent(v)
	return _u
}

// SetProcessedFiles sets the "processed_files" field.
func (_u *IngestionJobUpdate) SetProcessedFiles(v int) *IngestionJobUpdate {
	_u.mutation.ResetProcessedFiles()
	_u.mutation.SetProcessedFiles(v)
	return _u
}

// SetNillableProcessedFiles sets the "processed_files" field if the given value is not nil.
func (_u *IngestionJobUpdate) SetNillableProcessedFiles(v *int) *IngestionJobUpdate {
	if v != nil {
		_u.SetProcessedFiles(*v)
	}
	return _u
}

// AddProcessedFiles adds value to the "processed_files" field.
func (_u *IngestionJobUpdate) AddProcessedFiles(v int) *IngestionJobUpdate {
	_u.mutation.AddProcessedFiles(v)
	return _u
}

// SetTotalFiles sets the "total_files" field.
func (_u *IngestionJobUpdate) SetTotalFiles(v int) *IngestionJobUpdate {
	_u.mutation.ResetTotalFiles()
	_u.mutation.SetTotalFiles(v)
	return _u
}

// SetNillableTotalFiles sets the "total_files" field if the given value is not nil.
func (_u *IngestionJobUpdate) SetNillableTotalFiles(v *int) *IngestionJobUpdate {
	if v != nil {
		_u.SetTotalFiles(*v)
	}
	return _u
}

// AddTotalFiles adds value to the "total_files" field.
func (_u *IngestionJobUpdate) AddTotalFiles(v int) *IngestionJobUpdate {
	_u.mutation.AddTotalFiles(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *IngestionJobUpdate) SetErrorMessage(v string) *IngestionJobUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *IngestionJobUpdate) SetNillableErrorMessage(v *string) *IngestionJobUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *IngestionJobUpdate) ClearErrorMessage() *IngestionJobUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IngestionJobUpdate) SetUpdatedAt(v time.Time) *IngestionJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *IngestionJobUpdate) SetFinishedAt(v time.Time) *IngestionJobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *IngestionJobUpdate) SetNillableFinishedAt(v *time.Time) *IngestionJobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *IngestionJobUpdate) ClearFinishedAt() *IngestionJobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *IngestionJobUpdate) SetProject(v *Project) *IngestionJobUpdate {
	return _u.SetProjectID(v.ID)
}

// SetSource sets the "source" edge to the Source entity.
func (_u *IngestionJobUpdate) SetSource(v *Source) *IngestionJobUpdate {
	return _u.SetSourceID(v.ID)
}

// Mutation returns the IngestionJobMutation object of the builder.
func (_u *IngestionJobUpdate) Mutation() *IngestionJobMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *IngestionJobUpdate) ClearProject() *IngestionJobUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearSource clears the "source" edge to the Source entity.
func (_u *IngestionJobUpdate) ClearSource() *IngestionJobUpdate {
	_u.mutation.ClearSource()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IngestionJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IngestionJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IngestionJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IngestionJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IngestionJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ingestionjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IngestionJobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := ingestionjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IngestionJob.status": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IngestionJob.project"`)
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IngestionJob.source"`)
	}
	return nil
}

func (_u *IngestionJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ingestionjob.Table, ingestionjob.Columns, sqlgraph.NewFieldSpec(ingestionjob.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ingestionjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProgressPercent(); ok {
		_spec.SetField(ingestionjob.FieldProgressPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgressPercent(); ok {
		_spec.AddField(ingestionjob.FieldProgressPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProcessedFiles(); ok {
		_spec.SetField(ingestionjob.FieldProcessedFiles, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProcessedFiles(); ok {
		_spec.AddField(ingestionjob.FieldProcessedFiles, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalFiles(); ok {
		_spec.SetField(ingestionjob.FieldTotalFiles, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalFiles(); ok {
		_spec.AddField(ingestionjob.FieldTotalFiles, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(ingestionjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(ingestionjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ingestionjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(ingestionjob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(ingestionjob.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestionjob.ProjectTable,
			Columns: []string{ingestionjob.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestionjob.ProjectTable,
			Columns: []string{ingestionjob.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestionjob.SourceTable,
			Columns: []string{ingestionjob.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestionjob.SourceTable,
			Columns: []string{ingestionjob.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ingestionjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IngestionJobUpdateOne is the builder for updating a single IngestionJob entity.
type IngestionJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IngestionJobMutation
}

// SetProjectID sets the "project_id" field.
func (_u *IngestionJobUpdateOne) SetProjectID(v uuid.UUID) *IngestionJobUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *IngestionJobUpdateOne) SetNillableProjectID(v *uuid.UUID) *IngestionJobUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *IngestionJobUpdateOne) SetSourceID(v uuid.UUID) *IngestionJobUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *IngestionJobUpdateOne) SetNillableSourceID(v *uuid.UUID) *IngestionJobUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IngestionJobUpdateOne) SetStatus(v ingestionjob.Status) *IngestionJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IngestionJobUpdateOne) SetNillableStatus(v *ingestionjob.Status) *IngestionJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgressPercent sets the "progress_percent" field.
func (_u *IngestionJobUpdateOne) SetProgressPercent(v int) *IngestionJobUpdateOne {
	_u.mutation.ResetProgressPercent()
	_u.mutation.SetProgressPercent(v)
	return _u
}

// SetNillableProgressPercent sets the "progress_percent" field if the given value is not nil.
func (_u *IngestionJobUpdateOne) SetNillableProgressPercent(v *int) *IngestionJobUpdateOne {
	if v != nil {
		_u.SetProgressPercent(*v)
	}
	return _u
}

// AddProgressPercent adds value to the "progress_percent" field.
func (_u *IngestionJobUpdateOne) AddProgressPercent(v int) *IngestionJobUpdateOne {
	_u.mutation.AddProgressPercent(v)
	return _u
}

// SetProcessedFiles sets the "processed_files" field.
func (_u *IngestionJobUpdateOne) SetProcessedFiles(v int) *IngestionJobUpdateOne {
	_u.mutation.ResetProcessedFiles()
	_u.mutation.SetProcessedFiles(v)
	return _u
}

// SetNillableProcessedFiles sets the "processed_files" field if the given value is not nil.
func (_u *IngestionJobUpdateOne) SetNillableProcessedFiles(v *int) *IngestionJobUpdateOne {
	if v != nil {
		_u.SetProcessedFiles(*v)
	}
	return _u
}

// AddProcessedFiles adds value to the "processed_files" field.
func (_u *IngestionJobUpdateOne) AddProcessedFiles(v int) *IngestionJobUpdateOne {
	_u.mutation.AddProcessedFiles(v)
	return _u
}

// SetTotalFiles sets the "total_files" field.
func (_u *IngestionJobUpdateOne) SetTotalFiles(v int) *IngestionJobUpdateOne {
	_u.mutation.ResetTotalFiles()
	_u.mutation.SetTotalFiles(v)
	return _u
}

// SetNillableTotalFiles sets the "total_files" field if the given value is not nil.
func (_u *IngestionJobUpdateOne) SetNillableTotalFiles(v *int) *IngestionJobUpdateOne {
	if v != nil {
		_u.SetTotalFiles(*v)
	}
	return _u
}

// AddTotalFiles adds value to the "total_files" field.
func (_u *IngestionJobUpdateOne) AddTotalFiles(v int) *IngestionJobUpdateOne {
	_u.mutation.AddTotalFiles(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *IngestionJobUpdateOne) SetErrorMessage(v string) *IngestionJobUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *IngestionJobUpdateOne) SetNillableErrorMessage(v *string) *IngestionJobUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *IngestionJobUpdateOne) ClearErrorMessage() *IngestionJobUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IngestionJobUpdateOne) SetUpdatedAt(v time.Time) *IngestionJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *IngestionJobUpdateOne) SetFinishedAt(v time.Time) *IngestionJobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *IngestionJobUpdateOne) SetNillableFinishedAt(v *time.Time) *IngestionJobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *IngestionJobUpdateOne) ClearFinishedAt() *IngestionJobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *IngestionJobUpdateOne) SetProject(v *Project) *IngestionJobUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetSource sets the "source" edge to the Source entity.
func (_u *IngestionJobUpdateOne) SetSource(v *Source) *IngestionJobUpdateOne {
	return _u.SetSourceID(v.ID)
}

// Mutation returns the IngestionJobMutation object of the builder.
func (_u *IngestionJobUpdateOne) Mutation() *IngestionJobMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *IngestionJobUpdateOne) ClearProject() *IngestionJobUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearSource clears the "source" edge to the Source entity.
func (_u *IngestionJobUpdateOne) ClearSource() *IngestionJobUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// Where appends a list predicates to the IngestionJobUpdate builder.
func (_u *IngestionJobUpdateOne) Where(ps ...predicate.IngestionJob) *IngestionJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IngestionJobUpdateOne) Select(field string, fields ...string) *IngestionJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IngestionJob entity.
func (_u *IngestionJobUpdateOne) Save(ctx context.Context) (*IngestionJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IngestionJobUpdateOne) SaveX(ctx context.Context) *IngestionJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IngestionJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IngestionJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IngestionJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ingestionjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IngestionJobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := ingestionjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IngestionJob.status": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IngestionJob.project"`)
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IngestionJob.source"`)
	}
	return nil
}

func (_u *IngestionJobUpdateOne) sqlSave(ctx context.Context) (_node *IngestionJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ingestionjob.Table, ingestionjob.Columns, sqlgraph.NewFieldSpec(ingestionjob.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IngestionJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ingestionjob.FieldID)
		for _, f := range fields {
			if !ingestionjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ingestionjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ingestionjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProgressPercent(); ok {
		_spec.SetField(ingestionjob.FieldProgressPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgressPercent(); ok {
		_spec.AddField(ingestionjob.FieldProgressPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProcessedFiles(); ok {
		_spec.SetField(ingestionjob.FieldProcessedFiles, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProcessedFiles(); ok {
		_spec.AddField(ingestionjob.FieldProcessedFiles, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalFiles(); ok {
		_spec.SetField(ingestionjob.FieldTotalFiles, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalFiles(); ok {
		_spec.AddField(ingestionjob.FieldTotalFiles, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(ingestionjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(ingestionjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ingestionjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(ingestionjob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(ingestionjob.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestionjob.ProjectTable,
			Columns: []string{ingestionjob.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestionjob.ProjectTable,
			Columns: []string{ingestionjob.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestionjob.SourceTable,
			Columns: []string{ingestionjob.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestionjob.SourceTable,
			Columns: []string{ingestionjob.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IngestionJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ingestionjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
