// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/auditlog"
	"github.com/your-org/contextforge/internal/ent/databasesource"
	"github.com/your-org/contextforge/internal/ent/document"
	"github.com/your-org/contextforge/internal/ent/documentchunk"
	"github.com/your-org/contextforge/internal/ent/ingestionjob"
	"github.com/your-org/contextforge/internal/ent/predicate"
	"github.com/your-org/contextforge/internal/ent/project"
	"github.com/your-org/contextforge/internal/ent/source"
	"github.com/your-org/contextforge/internal/ent/user"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectUpdate) SetName(v string) *ProjectUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdate) SetDescription(v string) *ProjectUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableDescription(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectUpdate) ClearDescription() *ProjectUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *ProjectUpdate) SetOwnerUserID(v uuid.UUID) *ProjectUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableOwnerUserID(v *uuid.UUID) *ProjectUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetEmbeddingProvider sets the "embedding_provider" field.
func (_u *ProjectUpdate) SetEmbeddingProvider(v string) *ProjectUpdate {
	_u.mutation.SetEmbeddingProvider(v)
	return _u
}

// SetNillableEmbeddingProvider sets the "embedding_provider" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableEmbeddingProvider(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetEmbeddingProvider(*v)
	}
	return _u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_u *ProjectUpdate) SetEmbeddingModel(v string) *ProjectUpdate {
	_u.mutation.SetEmbeddingModel(v)
	return _u
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableEmbeddingModel(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetEmbeddingModel(*v)
	}
	return _u
}

// SetEmbeddingDimension sets the "embedding_dimension" field.
func (_u *ProjectUpdate) SetEmbeddingDimension(v int) *ProjectUpdate {
	_u.mutation.ResetEmbeddingDimension()
	_u.mutation.SetEmbeddingDimension(v)
	return _u
}

// SetNillableEmbeddingDimension sets the "embedding_dimension" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableEmbeddingDimension(v *int) *ProjectUpdate {
	if v != nil {
		_u.SetEmbeddingDimension(*v)
	}
	return _u
}

// AddEmbeddingDimension adds value to the "embedding_dimension" field.
func (_u *ProjectUpdate) AddEmbeddingDimension(v int) *ProjectUpdate {
	_u.mutation.AddEmbeddingDimension(v)
	return _u
}

// SetLlmProvider sets the "llm_provider" field.
func (_u *ProjectUpdate) SetLlmProvider(v string) *ProjectUpdate {
	_u.mutation.SetLlmProvider(v)
	return _u
}

// SetNillableLlmProvider sets the "llm_provider" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableLlmProvider(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetLlmProvider(*v)
	}
	return _u
}

// SetLlmModel sets the "llm_model" field.
func (_u *ProjectUpdate) SetLlmModel(v string) *ProjectUpdate {
	_u.mutation.SetLlmModel(v)
	return _u
}

// SetNillableLlmModel sets the "llm_model" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableLlmModel(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetLlmModel(*v)
	}
	return _u
}

// ClearLlmModel clears the value of the "llm_model" field.
func (_u *ProjectUpdate) ClearLlmModel() *ProjectUpdate {
	_u.mutation.ClearLlmModel()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdate) SetUpdatedAt(v time.Time) *ProjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ProjectUpdate) SetOwnerID(id uuid.UUID) *ProjectUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ProjectUpdate) SetOwner(v *User) *ProjectUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddSourceIDs adds the "sources" edge to the Source entity by IDs.
func (_u *ProjectUpdate) AddSourceIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddSourceIDs(ids...)
	return _u
}

// AddSources adds the "sources" edges to the Source entity.
func (_u *ProjectUpdate) AddSources(v ...*Source) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSourceIDs(ids...)
}

// AddDatabaseSourceIDs adds the "database_sources" edge to the DatabaseSource entity by IDs.
func (_u *ProjectUpdate) AddDatabaseSourceIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddDatabaseSourceIDs(ids...)
	return _u
}

// AddDatabaseSources adds the "database_sources" edges to the DatabaseSource entity.
func (_u *ProjectUpdate) AddDatabaseSources(v ...*DatabaseSource) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDatabaseSourceIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (_u *ProjectUpdate) AddDocumentIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocuments adds the "documents" edges to the Document entity.
func (_u *ProjectUpdate) AddDocuments(v ...*Document) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// AddChunkIDs adds the "chunks" edge to the DocumentChunk entity by IDs.
func (_u *ProjectUpdate) AddChunkIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddChunkIDs(ids...)
	return _u
}

// AddChunks adds the "chunks" edges to the DocumentChunk entity.
func (_u *ProjectUpdate) AddChunks(v ...*DocumentChunk) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChunkIDs(ids...)
}

// AddJobIDs adds the "jobs" edge to the IngestionJob entity by IDs.
func (_u *ProjectUpdate) AddJobIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddJobIDs(ids...)
	return _u
}

// AddJobs adds the "jobs" edges to the IngestionJob entity.
func (_u *ProjectUpdate) AddJobs(v ...*IngestionJob) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobIDs(ids...)
}

// AddAuditLogIDs adds the "audit_logs" edge to the AuditLog entity by IDs.
func (_u *ProjectUpdate) AddAuditLogIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddAuditLogIDs(ids...)
	return _u
}

// AddAuditLogs adds the "audit_logs" edges to the AuditLog entity.
func (_u *ProjectUpdate) AddAuditLogs(v ...*AuditLog) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuditLogIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ProjectUpdate) ClearOwner() *ProjectUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearSources clears all "sources" edges to the Source entity.
func (_u *ProjectUpdate) ClearSources() *ProjectUpdate {
	_u.mutation.ClearSources()
	return _u
}

// RemoveSourceIDs removes the "sources" edge to Source entities by IDs.
func (_u *ProjectUpdate) RemoveSourceIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveSourceIDs(ids...)
	return _u
}

// RemoveSources removes "sources" edges to Source entities.
func (_u *ProjectUpdate) RemoveSources(v ...*Source) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSourceIDs(ids...)
}

// ClearDatabaseSources clears all "database_sources" edges to the DatabaseSource entity.
func (_u *ProjectUpdate) ClearDatabaseSources() *ProjectUpdate {
	_u.mutation.ClearDatabaseSources()
	return _u
}

// RemoveDatabaseSourceIDs removes the "database_sources" edge to DatabaseSource entities by IDs.
func (_u *ProjectUpdate) RemoveDatabaseSourceIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveDatabaseSourceIDs(ids...)
	return _u
}

// RemoveDatabaseSources removes "database_sources" edges to DatabaseSource entities.
func (_u *ProjectUpdate) RemoveDatabaseSources(v ...*DatabaseSource) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDatabaseSourceIDs(ids...)
}

// ClearDocuments clears all "documents" edges to the Document entity.
func (_u *ProjectUpdate) ClearDocuments() *ProjectUpdate {
	_u.mutation.ClearDocuments()
	return _u
}

// RemoveDocumentIDs removes the "documents" edge to Document entities by IDs.
func (_u *ProjectUpdate) RemoveDocumentIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocuments removes "documents" edges to Document entities.
func (_u *ProjectUpdate) RemoveDocuments(v ...*Document) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// ClearChunks clears all "chunks" edges to the DocumentChunk entity.
func (_u *ProjectUpdate) ClearChunks() *ProjectUpdate {
	_u.mutation.ClearChunks()
	return _u
}

// RemoveChunkIDs removes the "chunks" edge to DocumentChunk entities by IDs.
func (_u *ProjectUpdate) RemoveChunkIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveChunkIDs(ids...)
	return _u
}

// RemoveChunks removes "chunks" edges to DocumentChunk entities.
func (_u *ProjectUpdate) RemoveChunks(v ...*DocumentChunk) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChunkIDs(ids...)
}

// ClearJobs clears all "jobs" edges to the IngestionJob entity.
func (_u *ProjectUpdate) ClearJobs() *ProjectUpdate {
	_u.mutation.ClearJobs()
	return _u
}

// RemoveJobIDs removes the "jobs" edge to IngestionJob entities by IDs.
func (_u *ProjectUpdate) RemoveJobIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveJobIDs(ids...)
	return _u
}

// RemoveJobs removes "jobs" edges to IngestionJob entities.
func (_u *ProjectUpdate) RemoveJobs(v ...*IngestionJob) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobIDs(ids...)
}

// ClearAuditLogs clears all "audit_logs" edges to the AuditLog entity.
func (_u *ProjectUpdate) ClearAuditLogs() *ProjectUpdate {
	_u.mutation.ClearAuditLogs()
	return _u
}

// RemoveAuditLogIDs removes the "audit_logs" edge to AuditLog entities by IDs.
func (_u *ProjectUpdate) RemoveAuditLogIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveAuditLogIDs(ids...)
	return _u
}

// RemoveAuditLogs removes "audit_logs" edges to AuditLog entities.
func (_u *ProjectUpdate) RemoveAuditLogs(v ...*AuditLog) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuditLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := project.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Project.description": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Project.owner"`)
	}
	return nil
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.EmbeddingProvider(); ok {
		_spec.SetField(project.FieldEmbeddingProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmbeddingModel(); ok {
		_spec.SetField(project.FieldEmbeddingModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmbeddingDimension(); ok {
		_spec.SetField(project.FieldEmbeddingDimension, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEmbeddingDimension(); ok {
		_spec.AddField(project.FieldEmbeddingDimension, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LlmProvider(); ok {
		_spec.SetField(project.FieldLlmProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.LlmModel(); ok {
		_spec.SetField(project.FieldLlmModel, field.TypeString, value)
	}
	if _u.mutation.LlmModelCleared() {
		_spec.ClearField(project.FieldLlmModel, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OwnerTable,
			Columns: []string{project.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OwnerTable,
			Columns: []string{project.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.SourcesTable,
			Columns: []string{project.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSourcesIDs(); len(nodes) > 0 && !_u.mutation.SourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.SourcesTable,
			Columns: []string{project.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.SourcesTable,
			Columns: []string{project.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DatabaseSourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DatabaseSourcesTable,
			Columns: []string{project.DatabaseSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(databasesource.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDatabaseSourcesIDs(); len(nodes) > 0 && !_u.mutation.DatabaseSourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DatabaseSourcesTable,
			Columns: []string{project.DatabaseSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(databasesource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DatabaseSourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DatabaseSourcesTable,
			Columns: []string{project.DatabaseSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(databasesource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DocumentsTable,
			Columns: []string{project.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !_u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DocumentsTable,
			Columns: []string{project.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DocumentsTable,
			Columns: []string{project.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChunksTable,
			Columns: []string{project.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChunksIDs(); len(nodes) > 0 && !_u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChunksTable,
			Columns: []string{project.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChunksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChunksTable,
			Columns: []string{project.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.JobsTable,
			Columns: []string{project.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingestionjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobsIDs(); len(nodes) > 0 && !_u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.JobsTable,
			Columns: []string{project.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingestionjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.JobsTable,
			Columns: []string{project.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingestionjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AuditLogsTable,
			Columns: []string{project.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuditLogsIDs(); len(nodes) > 0 && !_u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AuditLogsTable,
			Columns: []string{project.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AuditLogsTable,
			Columns: []string{project.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetName sets the "name" field.
func (_u *ProjectUpdateOne) SetName(v string) *ProjectUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdateOne) SetDescription(v string) *ProjectUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableDescription(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectUpdateOne) ClearDescription() *ProjectUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *ProjectUpdateOne) SetOwnerUserID(v uuid.UUID) *ProjectUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableOwnerUserID(v *uuid.UUID) *ProjectUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetEmbeddingProvider sets the "embedding_provider" field.
func (_u *ProjectUpdateOne) SetEmbeddingProvider(v string) *ProjectUpdateOne {
	_u.mutation.SetEmbeddingProvider(v)
	return _u
}

// SetNillableEmbeddingProvider sets the "embedding_provider" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableEmbeddingProvider(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetEmbeddingProvider(*v)
	}
	return _u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_u *ProjectUpdateOne) SetEmbeddingModel(v string) *ProjectUpdateOne {
	_u.mutation.SetEmbeddingModel(v)
	return _u
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableEmbeddingModel(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetEmbeddingModel(*v)
	}
	return _u
}

// SetEmbeddingDimension sets the "embedding_dimension" field.
func (_u *ProjectUpdateOne) SetEmbeddingDimension(v int) *ProjectUpdateOne {
	_u.mutation.ResetEmbeddingDimension()
	_u.mutation.SetEmbeddingDimension(v)
	return _u
}

// SetNillableEmbeddingDimension sets the "embedding_dimension" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableEmbeddingDimension(v *int) *ProjectUpdateOne {
	if v != nil {
		_u.SetEmbeddingDimension(*v)
	}
	return _u
}

// AddEmbeddingDimension adds value to the "embedding_dimension" field.
func (_u *ProjectUpdateOne) AddEmbeddingDimension(v int) *ProjectUpdateOne {
	_u.mutation.AddEmbeddingDimension(v)
	return _u
}

// SetLlmProvider sets the "llm_provider" field.
func (_u *ProjectUpdateOne) SetLlmProvider(v string) *ProjectUpdateOne {
	_u.mutation.SetLlmProvider(v)
	return _u
}

// SetNillableLlmProvider sets the "llm_provider" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableLlmProvider(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetLlmProvider(*v)
	}
	return _u
}

// SetLlmModel sets the "llm_model" field.
func (_u *ProjectUpdateOne) SetLlmModel(v string) *ProjectUpdateOne {
	_u.mutation.SetLlmModel(v)
	return _u
}

// SetNillableLlmModel sets the "llm_model" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableLlmModel(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetLlmModel(*v)
	}
	return _u
}

// ClearLlmModel clears the value of the "llm_model" field.
func (_u *ProjectUpdateOne) ClearLlmModel() *ProjectUpdateOne {
	_u.mutation.ClearLlmModel()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdateOne) SetUpdatedAt(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ProjectUpdateOne) SetOwnerID(id uuid.UUID) *ProjectUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ProjectUpdateOne) SetOwner(v *User) *ProjectUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddSourceIDs adds the "sources" edge to the Source entity by IDs.
func (_u *ProjectUpdateOne) AddSourceIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddSourceIDs(ids...)
	return _u
}

// AddSources adds the "sources" edges to the Source entity.
func (_u *ProjectUpdateOne) AddSources(v ...*Source) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSourceIDs(ids...)
}

// AddDatabaseSourceIDs adds the "database_sources" edge to the DatabaseSource entity by IDs.
func (_u *ProjectUpdateOne) AddDatabaseSourceIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddDatabaseSourceIDs(ids...)
	return _u
}

// AddDatabaseSources adds the "database_sources" edges to the DatabaseSource entity.
func (_u *ProjectUpdateOne) AddDatabaseSources(v ...*DatabaseSource) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDatabaseSourceIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (_u *ProjectUpdateOne) AddDocumentIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocuments adds the "documents" edges to the Document entity.
func (_u *ProjectUpdateOne) AddDocuments(v ...*Document) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// AddChunkIDs adds the "chunks" edge to the DocumentChunk entity by IDs.
func (_u *ProjectUpdateOne) AddChunkIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddChunkIDs(ids...)
	return _u
}

// AddChunks adds the "chunks" edges to the DocumentChunk entity.
func (_u *ProjectUpdateOne) AddChunks(v ...*DocumentChunk) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChunkIDs(ids...)
}

// AddJobIDs adds the "jobs" edge to the IngestionJob entity by IDs.
func (_u *ProjectUpdateOne) AddJobIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddJobIDs(ids...)
	return _u
}

// AddJobs adds the "jobs" edges to the IngestionJob entity.
func (_u *ProjectUpdateOne) AddJobs(v ...*IngestionJob) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobIDs(ids...)
}

// AddAuditLogIDs adds the "audit_logs" edge to the AuditLog entity by IDs.
func (_u *ProjectUpdateOne) AddAuditLogIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddAuditLogIDs(ids...)
	return _u
}

// AddAuditLogs adds the "audit_logs" edges to the AuditLog entity.
func (_u *ProjectUpdateOne) AddAuditLogs(v ...*AuditLog) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuditLogIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ProjectUpdateOne) ClearOwner() *ProjectUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearSources clears all "sources" edges to the Source entity.
func (_u *ProjectUpdateOne) ClearSources() *ProjectUpdateOne {
	_u.mutation.ClearSources()
	return _u
}

// RemoveSourceIDs removes the "sources" edge to Source entities by IDs.
func (_u *ProjectUpdateOne) RemoveSourceIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveSourceIDs(ids...)
	return _u
}

// RemoveSources removes "sources" edges to Source entities.
func (_u *ProjectUpdateOne) RemoveSources(v ...*Source) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSourceIDs(ids...)
}

// ClearDatabaseSources clears all "database_sources" edges to the DatabaseSource entity.
func (_u *ProjectUpdateOne) ClearDatabaseSources() *ProjectUpdateOne {
	_u.mutation.ClearDatabaseSources()
	return _u
}

// RemoveDatabaseSourceIDs removes the "database_sources" edge to DatabaseSource entities by IDs.
func (_u *ProjectUpdateOne) RemoveDatabaseSourceIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveDatabaseSourceIDs(ids...)
	return _u
}

// RemoveDatabaseSources removes "database_sources" edges to DatabaseSource entities.
func (_u *ProjectUpdateOne) RemoveDatabaseSources(v ...*DatabaseSource) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDatabaseSourceIDs(ids...)
}

// ClearDocuments clears all "documents" edges to the Document entity.
func (_u *ProjectUpdateOne) ClearDocuments() *ProjectUpdateOne {
	_u.mutation.ClearDocuments()
	return _u
}

// RemoveDocumentIDs removes the "documents" edge to Document entities by IDs.
func (_u *ProjectUpdateOne) RemoveDocumentIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocuments removes "documents" edges to Document entities.
func (_u *ProjectUpdateOne) RemoveDocuments(v ...*Document) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// ClearChunks clears all "chunks" edges to the DocumentChunk entity.
func (_u *ProjectUpdateOne) ClearChunks() *ProjectUpdateOne {
	_u.mutation.ClearChunks()
	return _u
}

// RemoveChunkIDs removes the "chunks" edge to DocumentChunk entities by IDs.
func (_u *ProjectUpdateOne) RemoveChunkIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveChunkIDs(ids...)
	return _u
}

// RemoveChunks removes "chunks" edges to DocumentChunk entities.
func (_u *ProjectUpdateOne) RemoveChunks(v ...*DocumentChunk) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChunkIDs(ids...)
}

// ClearJobs clears all "jobs" edges to the IngestionJob entity.
func (_u *ProjectUpdateOne) ClearJobs() *ProjectUpdateOne {
	_u.mutation.ClearJobs()
	return _u
}

// RemoveJobIDs removes the "jobs" edge to IngestionJob entities by IDs.
func (_u *ProjectUpdateOne) RemoveJobIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveJobIDs(ids...)
	return _u
}

// RemoveJobs removes "jobs" edges to IngestionJob entities.
func (_u *ProjectUpdateOne) RemoveJobs(v ...*IngestionJob) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobIDs(ids...)
}

// ClearAuditLogs clears all "audit_logs" edges to the AuditLog entity.
func (_u *ProjectUpdateOne) ClearAuditLogs() *ProjectUpdateOne {
	_u.mutation.ClearAuditLogs()
	return _u
}

// RemoveAuditLogIDs removes the "audit_logs" edge to AuditLog entities by IDs.
func (_u *ProjectUpdateOne) RemoveAuditLogIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveAuditLogIDs(ids...)
	return _u
}

// RemoveAuditLogs removes "audit_logs" edges to AuditLog entities.
func (_u *ProjectUpdateOne) RemoveAuditLogs(v ...*AuditLog) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuditLogIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := project.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Project.description": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Project.owner"`)
	}
	return nil
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.EmbeddingProvider(); ok {
		_spec.SetField(project.FieldEmbeddingProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmbeddingModel(); ok {
		_spec.SetField(project.FieldEmbeddingModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmbeddingDimension(); ok {
		_spec.SetField(project.FieldEmbeddingDimension, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEmbeddingDimension(); ok {
		_spec.AddField(project.FieldEmbeddingDimension, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LlmProvider(); ok {
		_spec.SetField(project.FieldLlmProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.LlmModel(); ok {
		_spec.SetField(project.FieldLlmModel, field.TypeString, value)
	}
	if _u.mutation.LlmModelCleared() {
		_spec.ClearField(project.FieldLlmModel, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OwnerTable,
			Columns: []string{project.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OwnerTable,
			Columns: []string{project.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.SourcesTable,
			Columns: []string{project.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSourcesIDs(); len(nodes) > 0 && !_u.mutation.SourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.SourcesTable,
			Columns: []string{project.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.SourcesTable,
			Columns: []string{project.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DatabaseSourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DatabaseSourcesTable,
			Columns: []string{project.DatabaseSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(databasesource.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDatabaseSourcesIDs(); len(nodes) > 0 && !_u.mutation.DatabaseSourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DatabaseSourcesTable,
			Columns: []string{project.DatabaseSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(databasesource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DatabaseSourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DatabaseSourcesTable,
			Columns: []string{project.DatabaseSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(databasesource.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DocumentsTable,
			Columns: []string{project.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !_u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DocumentsTable,
			Columns: []string{project.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.DocumentsTable,
			Columns: []string{project.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChunksTable,
			Columns: []string{project.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChunksIDs(); len(nodes) > 0 && !_u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChunksTable,
			Columns: []string{project.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChunksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChunksTable,
			Columns: []string{project.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.JobsTable,
			Columns: []string{project.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingestionjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobsIDs(); len(nodes) > 0 && !_u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.JobsTable,
			Columns: []string{project.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingestionjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.JobsTable,
			Columns: []string{project.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingestionjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AuditLogsTable,
			Columns: []string{project.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuditLogsIDs(); len(nodes) > 0 && !_u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AuditLogsTable,
			Columns: []string{project.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AuditLogsTable,
			Columns: []string{project.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
