// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/predicate"
	"github.com/your-org/contextforge/internal/ent/project"
	"github.com/your-org/contextforge/internal/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGithubID sets the "github_id" field.
func (_u *UserUpdate) SetGithubID(v int64) *UserUpdate {
	_u.mutation.ResetGithubID()
	_u.mutation.SetGithubID(v)
	return _u
}

// SetNillableGithubID sets the "github_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGithubID(v *int64) *UserUpdate {
	if v != nil {
		_u.SetGithubID(*v)
	}
	return _u
}

// AddGithubID adds value to the "github_id" field.
func (_u *UserUpdate) AddGithubID(v int64) *UserUpdate {
	_u.mutation.AddGithubID(v)
	return _u
}

// ClearGithubID clears the value of the "github_id" field.
func (_u *UserUpdate) ClearGithubID() *UserUpdate {
	_u.mutation.ClearGithubID()
	return _u
}

// SetGithubLogin sets the "github_login" field.
func (_u *UserUpdate) SetGithubLogin(v string) *UserUpdate {
	_u.mutation.SetGithubLogin(v)
	return _u
}

// SetNillableGithubLogin sets the "github_login" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGithubLogin(v *string) *UserUpdate {
	if v != nil {
		_u.SetGithubLogin(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *UserUpdate) ClearName() *UserUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdate) SetAvatarURL(v string) *UserUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatarURL(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdate) ClearAvatarURL() *UserUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetEncryptedAccessToken sets the "encrypted_access_token" field.
func (_u *UserUpdate) SetEncryptedAccessToken(v string) *UserUpdate {
	_u.mutation.SetEncryptedAccessToken(v)
	return _u
}

// SetNillableEncryptedAccessToken sets the "encrypted_access_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEncryptedAccessToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetEncryptedAccessToken(*v)
	}
	return _u
}

// ClearEncryptedAccessToken clears the value of the "encrypted_access_token" field.
func (_u *UserUpdate) ClearEncryptedAccessToken() *UserUpdate {
	_u.mutation.ClearEncryptedAccessToken()
	return _u
}

// SetEncryptedRefreshToken sets the "encrypted_refresh_token" field.
func (_u *UserUpdate) SetEncryptedRefreshToken(v string) *UserUpdate {
	_u.mutation.SetEncryptedRefreshToken(v)
	return _u
}

// SetNillableEncryptedRefreshToken sets the "encrypted_refresh_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEncryptedRefreshToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetEncryptedRefreshToken(*v)
	}
	return _u
}

// ClearEncryptedRefreshToken clears the value of the "encrypted_refresh_token" field.
func (_u *UserUpdate) ClearEncryptedRefreshToken() *UserUpdate {
	_u.mutation.ClearEncryptedRefreshToken()
	return _u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_u *UserUpdate) SetTokenExpiresAt(v time.Time) *UserUpdate {
	_u.mutation.SetTokenExpiresAt(v)
	return _u
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTokenExpiresAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetTokenExpiresAt(*v)
	}
	return _u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (_u *UserUpdate) ClearTokenExpiresAt() *UserUpdate {
	_u.mutation.ClearTokenExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_u *UserUpdate) AddProjectIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddProjectIDs(ids...)
	return _u
}

// AddProjects adds the "projects" edges to the Project entity.
func (_u *UserUpdate) AddProjects(v ...*Project) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearProjects clears all "projects" edges to the Project entity.
func (_u *UserUpdate) ClearProjects() *UserUpdate {
	_u.mutation.ClearProjects()
	return _u
}

// RemoveProjectIDs removes the "projects" edge to Project entities by IDs.
func (_u *UserUpdate) RemoveProjectIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveProjectIDs(ids...)
	return _u
}

// RemoveProjects removes "projects" edges to Project entities.
func (_u *UserUpdate) RemoveProjects(v ...*Project) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.GithubLogin(); ok {
		if err := user.GithubLoginValidator(v); err != nil {
			return &ValidationError{Name: "github_login", err: fmt.Errorf(`ent: validator failed for field "User.github_login": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GithubID(); ok {
		_spec.SetField(user.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGithubID(); ok {
		_spec.AddField(user.FieldGithubID, field.TypeInt64, value)
	}
	if _u.mutation.GithubIDCleared() {
		_spec.ClearField(user.FieldGithubID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GithubLogin(); ok {
		_spec.SetField(user.FieldGithubLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(user.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptedAccessToken(); ok {
		_spec.SetField(user.FieldEncryptedAccessToken, field.TypeString, value)
	}
	if _u.mutation.EncryptedAccessTokenCleared() {
		_spec.ClearField(user.FieldEncryptedAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptedRefreshToken(); ok {
		_spec.SetField(user.FieldEncryptedRefreshToken, field.TypeString, value)
	}
	if _u.mutation.EncryptedRefreshTokenCleared() {
		_spec.ClearField(user.FieldEncryptedRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiresAt(); ok {
		_spec.SetField(user.FieldTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiresAtCleared() {
		_spec.ClearField(user.FieldTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProjectsTable,
			Columns: []string{user.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectsIDs(); len(nodes) > 0 && !_u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProjectsTable,
			Columns: []string{user.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProjectsTable,
			Columns: []string{user.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetGithubID sets the "github_id" field.
func (_u *UserUpdateOne) SetGithubID(v int64) *UserUpdateOne {
	_u.mutation.ResetGithubID()
	_u.mutation.SetGithubID(v)
	return _u
}

// SetNillableGithubID sets the "github_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGithubID(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetGithubID(*v)
	}
	return _u
}

// AddGithubID adds value to the "github_id" field.
func (_u *UserUpdateOne) AddGithubID(v int64) *UserUpdateOne {
	_u.mutation.AddGithubID(v)
	return _u
}

// ClearGithubID clears the value of the "github_id" field.
func (_u *UserUpdateOne) ClearGithubID() *UserUpdateOne {
	_u.mutation.ClearGithubID()
	return _u
}

// SetGithubLogin sets the "github_login" field.
func (_u *UserUpdateOne) SetGithubLogin(v string) *UserUpdateOne {
	_u.mutation.SetGithubLogin(v)
	return _u
}

// SetNillableGithubLogin sets the "github_login" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGithubLogin(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGithubLogin(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *UserUpdateOne) ClearName() *UserUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdateOne) SetAvatarURL(v string) *UserUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatarURL(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdateOne) ClearAvatarURL() *UserUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetEncryptedAccessToken sets the "encrypted_access_token" field.
func (_u *UserUpdateOne) SetEncryptedAccessToken(v string) *UserUpdateOne {
	_u.mutation.SetEncryptedAccessToken(v)
	return _u
}

// SetNillableEncryptedAccessToken sets the "encrypted_access_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEncryptedAccessToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEncryptedAccessToken(*v)
	}
	return _u
}

// ClearEncryptedAccessToken clears the value of the "encrypted_access_token" field.
func (_u *UserUpdateOne) ClearEncryptedAccessToken() *UserUpdateOne {
	_u.mutation.ClearEncryptedAccessToken()
	return _u
}

// SetEncryptedRefreshToken sets the "encrypted_refresh_token" field.
func (_u *UserUpdateOne) SetEncryptedRefreshToken(v string) *UserUpdateOne {
	_u.mutation.SetEncryptedRefreshToken(v)
	return _u
}

// SetNillableEncryptedRefreshToken sets the "encrypted_refresh_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEncryptedRefreshToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEncryptedRefreshToken(*v)
	}
	return _u
}

// ClearEncryptedRefreshToken clears the value of the "encrypted_refresh_token" field.
func (_u *UserUpdateOne) ClearEncryptedRefreshToken() *UserUpdateOne {
	_u.mutation.ClearEncryptedRefreshToken()
	return _u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_u *UserUpdateOne) SetTokenExpiresAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetTokenExpiresAt(v)
	return _u
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTokenExpiresAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetTokenExpiresAt(*v)
	}
	return _u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (_u *UserUpdateOne) ClearTokenExpiresAt() *UserUpdateOne {
	_u.mutation.ClearTokenExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_u *UserUpdateOne) AddProjectIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddProjectIDs(ids...)
	return _u
}

// AddProjects adds the "projects" edges to the Project entity.
func (_u *UserUpdateOne) AddProjects(v ...*Project) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearProjects clears all "projects" edges to the Project entity.
func (_u *UserUpdateOne) ClearProjects() *UserUpdateOne {
	_u.mutation.ClearProjects()
	return _u
}

// RemoveProjectIDs removes the "projects" edge to Project entities by IDs.
func (_u *UserUpdateOne) RemoveProjectIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveProjectIDs(ids...)
	return _u
}

// RemoveProjects removes "projects" edges to Project entities.
func (_u *UserUpdateOne) RemoveProjects(v ...*Project) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.GithubLogin(); ok {
		if err := user.GithubLoginValidator(v); err != nil {
			return &ValidationError{Name: "github_login", err: fmt.Errorf(`ent: validator failed for field "User.github_login": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GithubID(); ok {
		_spec.SetField(user.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGithubID(); ok {
		_spec.AddField(user.FieldGithubID, field.TypeInt64, value)
	}
	if _u.mutation.GithubIDCleared() {
		_spec.ClearField(user.FieldGithubID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GithubLogin(); ok {
		_spec.SetField(user.FieldGithubLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(user.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptedAccessToken(); ok {
		_spec.SetField(user.FieldEncryptedAccessToken, field.TypeString, value)
	}
	if _u.mutation.EncryptedAccessTokenCleared() {
		_spec.ClearField(user.FieldEncryptedAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptedRefreshToken(); ok {
		_spec.SetField(user.FieldEncryptedRefreshToken, field.TypeString, value)
	}
	if _u.mutation.EncryptedRefreshTokenCleared() {
		_spec.ClearField(user.FieldEncryptedRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiresAt(); ok {
		_spec.SetField(user.FieldTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiresAtCleared() {
		_spec.ClearField(user.FieldTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProjectsTable,
			Columns: []string{user.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectsIDs(); len(nodes) > 0 && !_u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProjectsTable,
			Columns: []string{user.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProjectsTable,
			Columns: []string{user.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
