// Code generated by ent, DO NOT EDIT.

package databasesource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldID, id))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldSourceID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldProjectID, v))
}

// DatabaseType applies equality check predicate on the "database_type" field. It's identical to DatabaseTypeEQ.
func DatabaseType(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldDatabaseType, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldHost, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldPort, v))
}

// DatabaseName applies equality check predicate on the "database_name" field. It's identical to DatabaseNameEQ.
func DatabaseName(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldDatabaseName, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldUsername, v))
}

// EncryptedConnectionURL applies equality check predicate on the "encrypted_connection_url" field. It's identical to EncryptedConnectionURLEQ.
func EncryptedConnectionURL(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldEncryptedConnectionURL, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldStatus, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldLastError, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldLastSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldSourceID, vs...))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldProjectID, vs...))
}

// DatabaseTypeEQ applies the EQ predicate on the "database_type" field.
func DatabaseTypeEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldDatabaseType, v))
}

// DatabaseTypeNEQ applies the NEQ predicate on the "database_type" field.
func DatabaseTypeNEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldDatabaseType, v))
}

// DatabaseTypeIn applies the In predicate on the "database_type" field.
func DatabaseTypeIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldDatabaseType, vs...))
}

// DatabaseTypeNotIn applies the NotIn predicate on the "database_type" field.
func DatabaseTypeNotIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldDatabaseType, vs...))
}

// DatabaseTypeGT applies the GT predicate on the "database_type" field.
func DatabaseTypeGT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldDatabaseType, v))
}

// DatabaseTypeGTE applies the GTE predicate on the "database_type" field.
func DatabaseTypeGTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldDatabaseType, v))
}

// DatabaseTypeLT applies the LT predicate on the "database_type" field.
func DatabaseTypeLT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldDatabaseType, v))
}

// DatabaseTypeLTE applies the LTE predicate on the "database_type" field.
func DatabaseTypeLTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldDatabaseType, v))
}

// DatabaseTypeContains applies the Contains predicate on the "database_type" field.
func DatabaseTypeContains(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContains(FieldDatabaseType, v))
}

// DatabaseTypeHasPrefix applies the HasPrefix predicate on the "database_type" field.
func DatabaseTypeHasPrefix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasPrefix(FieldDatabaseType, v))
}

// DatabaseTypeHasSuffix applies the HasSuffix predicate on the "database_type" field.
func DatabaseTypeHasSuffix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasSuffix(FieldDatabaseType, v))
}

// DatabaseTypeEqualFold applies the EqualFold predicate on the "database_type" field.
func DatabaseTypeEqualFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEqualFold(FieldDatabaseType, v))
}

// DatabaseTypeContainsFold applies the ContainsFold predicate on the "database_type" field.
func DatabaseTypeContainsFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContainsFold(FieldDatabaseType, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContainsFold(FieldHost, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldPort, v))
}

// DatabaseNameEQ applies the EQ predicate on the "database_name" field.
func DatabaseNameEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldDatabaseName, v))
}

// DatabaseNameNEQ applies the NEQ predicate on the "database_name" field.
func DatabaseNameNEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldDatabaseName, v))
}

// DatabaseNameIn applies the In predicate on the "database_name" field.
func DatabaseNameIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldDatabaseName, vs...))
}

// DatabaseNameNotIn applies the NotIn predicate on the "database_name" field.
func DatabaseNameNotIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldDatabaseName, vs...))
}

// DatabaseNameGT applies the GT predicate on the "database_name" field.
func DatabaseNameGT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldDatabaseName, v))
}

// DatabaseNameGTE applies the GTE predicate on the "database_name" field.
func DatabaseNameGTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldDatabaseName, v))
}

// DatabaseNameLT applies the LT predicate on the "database_name" field.
func DatabaseNameLT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldDatabaseName, v))
}

// DatabaseNameLTE applies the LTE predicate on the "database_name" field.
func DatabaseNameLTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldDatabaseName, v))
}

// DatabaseNameContains applies the Contains predicate on the "database_name" field.
func DatabaseNameContains(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContains(FieldDatabaseName, v))
}

// DatabaseNameHasPrefix applies the HasPrefix predicate on the "database_name" field.
func DatabaseNameHasPrefix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasPrefix(FieldDatabaseName, v))
}

// DatabaseNameHasSuffix applies the HasSuffix predicate on the "database_name" field.
func DatabaseNameHasSuffix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasSuffix(FieldDatabaseName, v))
}

// DatabaseNameEqualFold applies the EqualFold predicate on the "database_name" field.
func DatabaseNameEqualFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEqualFold(FieldDatabaseName, v))
}

// DatabaseNameContainsFold applies the ContainsFold predicate on the "database_name" field.
func DatabaseNameContainsFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContainsFold(FieldDatabaseName, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContainsFold(FieldUsername, v))
}

// EncryptedConnectionURLEQ applies the EQ predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldEncryptedConnectionURL, v))
}

// EncryptedConnectionURLNEQ applies the NEQ predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLNEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldEncryptedConnectionURL, v))
}

// EncryptedConnectionURLIn applies the In predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldEncryptedConnectionURL, vs...))
}

// EncryptedConnectionURLNotIn applies the NotIn predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLNotIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldEncryptedConnectionURL, vs...))
}

// EncryptedConnectionURLGT applies the GT predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLGT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldEncryptedConnectionURL, v))
}

// EncryptedConnectionURLGTE applies the GTE predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLGTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldEncryptedConnectionURL, v))
}

// EncryptedConnectionURLLT applies the LT predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLLT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldEncryptedConnectionURL, v))
}

// EncryptedConnectionURLLTE applies the LTE predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLLTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldEncryptedConnectionURL, v))
}

// EncryptedConnectionURLContains applies the Contains predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLContains(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContains(FieldEncryptedConnectionURL, v))
}

// EncryptedConnectionURLHasPrefix applies the HasPrefix predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLHasPrefix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasPrefix(FieldEncryptedConnectionURL, v))
}

// EncryptedConnectionURLHasSuffix applies the HasSuffix predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLHasSuffix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasSuffix(FieldEncryptedConnectionURL, v))
}

// EncryptedConnectionURLEqualFold applies the EqualFold predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLEqualFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEqualFold(FieldEncryptedConnectionURL, v))
}

// EncryptedConnectionURLContainsFold applies the ContainsFold predicate on the "encrypted_connection_url" field.
func EncryptedConnectionURLContainsFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContainsFold(FieldEncryptedConnectionURL, v))
}

// ConfigurationIsNil applies the IsNil predicate on the "configuration" field.
func ConfigurationIsNil() predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIsNull(FieldConfiguration))
}

// ConfigurationNotNil applies the NotNil predicate on the "configuration" field.
func ConfigurationNotNil() predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotNull(FieldConfiguration))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContainsFold(FieldStatus, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldContainsFold(FieldLastError, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotNull(FieldLastSyncedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSource applies the HasEdge predicate on the "source" edge.
func HasSource() predicate.DatabaseSource {
	return predicate.DatabaseSource(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, SourceTable, SourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceWith applies the HasEdge predicate on the "source" edge with a given conditions (other predicates).
func HasSourceWith(preds ...predicate.Source) predicate.DatabaseSource {
	return predicate.DatabaseSource(func(s *sql.Selector) {
		step := newSourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.DatabaseSource {
	return predicate.DatabaseSource(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.DatabaseSource {
	return predicate.DatabaseSource(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DatabaseSource) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DatabaseSource) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DatabaseSource) predicate.DatabaseSource {
	return predicate.DatabaseSource(sql.NotPredicates(p))
}
