// Code generated by ent, DO NOT EDIT.

package source

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldProjectID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldType, v))
}

// RepoOwner applies equality check predicate on the "repo_owner" field. It's identical to RepoOwnerEQ.
func RepoOwner(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldRepoOwner, v))
}

// RepoName applies equality check predicate on the "repo_name" field. It's identical to RepoNameEQ.
func RepoName(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldRepoName, v))
}

// Branch applies equality check predicate on the "branch" field. It's identical to BranchEQ.
func Branch(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldBranch, v))
}

// LastCommitHash applies equality check predicate on the "last_commit_hash" field. It's identical to LastCommitHashEQ.
func LastCommitHash(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldLastCommitHash, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldLastSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldProjectID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Source {
	return predicate.Source(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Source {
	return predicate.Source(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Source {
	return predicate.Source(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Source {
	return predicate.Source(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Source {
	return predicate.Source(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Source {
	return predicate.Source(sql.FieldContainsFold(FieldType, v))
}

// RepoOwnerEQ applies the EQ predicate on the "repo_owner" field.
func RepoOwnerEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldRepoOwner, v))
}

// RepoOwnerNEQ applies the NEQ predicate on the "repo_owner" field.
func RepoOwnerNEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldRepoOwner, v))
}

// RepoOwnerIn applies the In predicate on the "repo_owner" field.
func RepoOwnerIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldRepoOwner, vs...))
}

// RepoOwnerNotIn applies the NotIn predicate on the "repo_owner" field.
func RepoOwnerNotIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldRepoOwner, vs...))
}

// RepoOwnerGT applies the GT predicate on the "repo_owner" field.
func RepoOwnerGT(v string) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldRepoOwner, v))
}

// RepoOwnerGTE applies the GTE predicate on the "repo_owner" field.
func RepoOwnerGTE(v string) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldRepoOwner, v))
}

// RepoOwnerLT applies the LT predicate on the "repo_owner" field.
func RepoOwnerLT(v string) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldRepoOwner, v))
}

// RepoOwnerLTE applies the LTE predicate on the "repo_owner" field.
func RepoOwnerLTE(v string) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldRepoOwner, v))
}

// RepoOwnerContains applies the Contains predicate on the "repo_owner" field.
func RepoOwnerContains(v string) predicate.Source {
	return predicate.Source(sql.FieldContains(FieldRepoOwner, v))
}

// RepoOwnerHasPrefix applies the HasPrefix predicate on the "repo_owner" field.
func RepoOwnerHasPrefix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasPrefix(FieldRepoOwner, v))
}

// RepoOwnerHasSuffix applies the HasSuffix predicate on the "repo_owner" field.
func RepoOwnerHasSuffix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasSuffix(FieldRepoOwner, v))
}

// RepoOwnerIsNil applies the IsNil predicate on the "repo_owner" field.
func RepoOwnerIsNil() predicate.Source {
	return predicate.Source(sql.FieldIsNull(FieldRepoOwner))
}

// RepoOwnerNotNil applies the NotNil predicate on the "repo_owner" field.
func RepoOwnerNotNil() predicate.Source {
	return predicate.Source(sql.FieldNotNull(FieldRepoOwner))
}

// RepoOwnerEqualFold applies the EqualFold predicate on the "repo_owner" field.
func RepoOwnerEqualFold(v string) predicate.Source {
	return predicate.Source(sql.FieldEqualFold(FieldRepoOwner, v))
}

// RepoOwnerContainsFold applies the ContainsFold predicate on the "repo_owner" field.
func RepoOwnerContainsFold(v string) predicate.Source {
	return predicate.Source(sql.FieldContainsFold(FieldRepoOwner, v))
}

// RepoNameEQ applies the EQ predicate on the "repo_name" field.
func RepoNameEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldRepoName, v))
}

// RepoNameNEQ applies the NEQ predicate on the "repo_name" field.
func RepoNameNEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldRepoName, v))
}

// RepoNameIn applies the In predicate on the "repo_name" field.
func RepoNameIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldRepoName, vs...))
}

// RepoNameNotIn applies the NotIn predicate on the "repo_name" field.
func RepoNameNotIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldRepoName, vs...))
}

// RepoNameGT applies the GT predicate on the "repo_name" field.
func RepoNameGT(v string) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldRepoName, v))
}

// RepoNameGTE applies the GTE predicate on the "repo_name" field.
func RepoNameGTE(v string) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldRepoName, v))
}

// RepoNameLT applies the LT predicate on the "repo_name" field.
func RepoNameLT(v string) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldRepoName, v))
}

// RepoNameLTE applies the LTE predicate on the "repo_name" field.
func RepoNameLTE(v string) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldRepoName, v))
}

// RepoNameContains applies the Contains predicate on the "repo_name" field.
func RepoNameContains(v string) predicate.Source {
	return predicate.Source(sql.FieldContains(FieldRepoName, v))
}

// RepoNameHasPrefix applies the HasPrefix predicate on the "repo_name" field.
func RepoNameHasPrefix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasPrefix(FieldRepoName, v))
}

// RepoNameHasSuffix applies the HasSuffix predicate on the "repo_name" field.
func RepoNameHasSuffix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasSuffix(FieldRepoName, v))
}

// RepoNameIsNil applies the IsNil predicate on the "repo_name" field.
func RepoNameIsNil() predicate.Source {
	return predicate.Source(sql.FieldIsNull(FieldRepoName))
}

// RepoNameNotNil applies the NotNil predicate on the "repo_name" field.
func RepoNameNotNil() predicate.Source {
	return predicate.Source(sql.FieldNotNull(FieldRepoName))
}

// RepoNameEqualFold applies the EqualFold predicate on the "repo_name" field.
func RepoNameEqualFold(v string) predicate.Source {
	return predicate.Source(sql.FieldEqualFold(FieldRepoName, v))
}

// RepoNameContainsFold applies the ContainsFold predicate on the "repo_name" field.
func RepoNameContainsFold(v string) predicate.Source {
	return predicate.Source(sql.FieldContainsFold(FieldRepoName, v))
}

// BranchEQ applies the EQ predicate on the "branch" field.
func BranchEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldBranch, v))
}

// BranchNEQ applies the NEQ predicate on the "branch" field.
func BranchNEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldBranch, v))
}

// BranchIn applies the In predicate on the "branch" field.
func BranchIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldBranch, vs...))
}

// BranchNotIn applies the NotIn predicate on the "branch" field.
func BranchNotIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldBranch, vs...))
}

// BranchGT applies the GT predicate on the "branch" field.
func BranchGT(v string) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldBranch, v))
}

// BranchGTE applies the GTE predicate on the "branch" field.
func BranchGTE(v string) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldBranch, v))
}

// BranchLT applies the LT predicate on the "branch" field.
func BranchLT(v string) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldBranch, v))
}

// BranchLTE applies the LTE predicate on the "branch" field.
func BranchLTE(v string) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldBranch, v))
}

// BranchContains applies the Contains predicate on the "branch" field.
func BranchContains(v string) predicate.Source {
	return predicate.Source(sql.FieldContains(FieldBranch, v))
}

// BranchHasPrefix applies the HasPrefix predicate on the "branch" field.
func BranchHasPrefix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasPrefix(FieldBranch, v))
}

// BranchHasSuffix applies the HasSuffix predicate on the "branch" field.
func BranchHasSuffix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasSuffix(FieldBranch, v))
}

// BranchIsNil applies the IsNil predicate on the "branch" field.
func BranchIsNil() predicate.Source {
	return predicate.Source(sql.FieldIsNull(FieldBranch))
}

// BranchNotNil applies the NotNil predicate on the "branch" field.
func BranchNotNil() predicate.Source {
	return predicate.Source(sql.FieldNotNull(FieldBranch))
}

// BranchEqualFold applies the EqualFold predicate on the "branch" field.
func BranchEqualFold(v string) predicate.Source {
	return predicate.Source(sql.FieldEqualFold(FieldBranch, v))
}

// BranchContainsFold applies the ContainsFold predicate on the "branch" field.
func BranchContainsFold(v string) predicate.Source {
	return predicate.Source(sql.FieldContainsFold(FieldBranch, v))
}

// LastCommitHashEQ applies the EQ predicate on the "last_commit_hash" field.
func LastCommitHashEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldLastCommitHash, v))
}

// LastCommitHashNEQ applies the NEQ predicate on the "last_commit_hash" field.
func LastCommitHashNEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldLastCommitHash, v))
}

// LastCommitHashIn applies the In predicate on the "last_commit_hash" field.
func LastCommitHashIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldLastCommitHash, vs...))
}

// LastCommitHashNotIn applies the NotIn predicate on the "last_commit_hash" field.
func LastCommitHashNotIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldLastCommitHash, vs...))
}

// LastCommitHashGT applies the GT predicate on the "last_commit_hash" field.
func LastCommitHashGT(v string) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldLastCommitHash, v))
}

// LastCommitHashGTE applies the GTE predicate on the "last_commit_hash" field.
func LastCommitHashGTE(v string) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldLastCommitHash, v))
}

// LastCommitHashLT applies the LT predicate on the "last_commit_hash" field.
func LastCommitHashLT(v string) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldLastCommitHash, v))
}

// LastCommitHashLTE applies the LTE predicate on the "last_commit_hash" field.
func LastCommitHashLTE(v string) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldLastCommitHash, v))
}

// LastCommitHashContains applies the Contains predicate on the "last_commit_hash" field.
func LastCommitHashContains(v string) predicate.Source {
	return predicate.Source(sql.FieldContains(FieldLastCommitHash, v))
}

// LastCommitHashHasPrefix applies the HasPrefix predicate on the "last_commit_hash" field.
func LastCommitHashHasPrefix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasPrefix(FieldLastCommitHash, v))
}

// LastCommitHashHasSuffix applies the HasSuffix predicate on the "last_commit_hash" field.
func LastCommitHashHasSuffix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasSuffix(FieldLastCommitHash, v))
}

// LastCommitHashIsNil applies the IsNil predicate on the "last_commit_hash" field.
func LastCommitHashIsNil() predicate.Source {
	return predicate.Source(sql.FieldIsNull(FieldLastCommitHash))
}

// LastCommitHashNotNil applies the NotNil predicate on the "last_commit_hash" field.
func LastCommitHashNotNil() predicate.Source {
	return predicate.Source(sql.FieldNotNull(FieldLastCommitHash))
}

// LastCommitHashEqualFold applies the EqualFold predicate on the "last_commit_hash" field.
func LastCommitHashEqualFold(v string) predicate.Source {
	return predicate.Source(sql.FieldEqualFold(FieldLastCommitHash, v))
}

// LastCommitHashContainsFold applies the ContainsFold predicate on the "last_commit_hash" field.
func LastCommitHashContainsFold(v string) predicate.Source {
	return predicate.Source(sql.FieldContainsFold(FieldLastCommitHash, v))
}

// SyncStatusEQ applies the EQ predicate on the "sync_status" field.
func SyncStatusEQ(v SyncStatus) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldSyncStatus, v))
}

// SyncStatusNEQ applies the NEQ predicate on the "sync_status" field.
func SyncStatusNEQ(v SyncStatus) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldSyncStatus, v))
}

// SyncStatusIn applies the In predicate on the "sync_status" field.
func SyncStatusIn(vs ...SyncStatus) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldSyncStatus, vs...))
}

// SyncStatusNotIn applies the NotIn predicate on the "sync_status" field.
func SyncStatusNotIn(vs ...SyncStatus) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldSyncStatus, vs...))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.Source {
	return predicate.Source(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.Source {
	return predicate.Source(sql.FieldNotNull(FieldLastSyncedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Source {
	return predicate.Source(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Source {
	return predicate.Source(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDocuments applies the HasEdge predicate on the "documents" edge.
func HasDocuments() predicate.Source {
	return predicate.Source(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DocumentsTable, DocumentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentsWith applies the HasEdge predicate on the "documents" edge with a given conditions (other predicates).
func HasDocumentsWith(preds ...predicate.Document) predicate.Source {
	return predicate.Source(func(s *sql.Selector) {
		step := newDocumentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasJobs applies the HasEdge predicate on the "jobs" edge.
func HasJobs() predicate.Source {
	return predicate.Source(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, JobsTable, JobsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJobsWith applies the HasEdge predicate on the "jobs" edge with a given conditions (other predicates).
func HasJobsWith(preds ...predicate.IngestionJob) predicate.Source {
	return predicate.Source(func(s *sql.Selector) {
		step := newJobsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDatabaseSource applies the HasEdge predicate on the "database_source" edge.
func HasDatabaseSource() predicate.Source {
	return predicate.Source(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, DatabaseSourceTable, DatabaseSourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDatabaseSourceWith applies the HasEdge predicate on the "database_source" edge with a given conditions (other predicates).
func HasDatabaseSourceWith(preds ...predicate.DatabaseSource) predicate.Source {
	return predicate.Source(func(s *sql.Selector) {
		step := newDatabaseSourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Source) predicate.Source {
	return predicate.Source(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Source) predicate.Source {
	return predicate.Source(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Source) predicate.Source {
	return predicate.Source(sql.NotPredicates(p))
}
