// Code generated by ent, DO NOT EDIT.

package project

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldEmbeddingProvider holds the string denoting the embedding_provider field in the database.
	FieldEmbeddingProvider = "embedding_provider"
	// FieldEmbeddingModel holds the string denoting the embedding_model field in the database.
	FieldEmbeddingModel = "embedding_model"
	// FieldEmbeddingDimension holds the string denoting the embedding_dimension field in the database.
	FieldEmbeddingDimension = "embedding_dimension"
	// FieldLlmProvider holds the string denoting the llm_provider field in the database.
	FieldLlmProvider = "llm_provider"
	// FieldLlmModel holds the string denoting the llm_model field in the database.
	FieldLlmModel = "llm_model"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeSources holds the string denoting the sources edge name in mutations.
	EdgeSources = "sources"
	// EdgeDatabaseSources holds the string denoting the database_sources edge name in mutations.
	EdgeDatabaseSources = "database_sources"
	// EdgeDocuments holds the string denoting the documents edge name in mutations.
	EdgeDocuments = "documents"
	// EdgeChunks holds the string denoting the chunks edge name in mutations.
	EdgeChunks = "chunks"
	// EdgeJobs holds the string denoting the jobs edge name in mutations.
	EdgeJobs = "jobs"
	// EdgeAuditLogs holds the string denoting the audit_logs edge name in mutations.
	EdgeAuditLogs = "audit_logs"
	// Table holds the table name of the project in the database.
	Table = "projects"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "projects"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_user_id"
	// SourcesTable is the table that holds the sources relation/edge.
	SourcesTable = "sources"
	// SourcesInverseTable is the table name for the Source entity.
	// It exists in this package in order to avoid circular dependency with the "source" package.
	SourcesInverseTable = "sources"
	// SourcesColumn is the table column denoting the sources relation/edge.
	SourcesColumn = "project_id"
	// DatabaseSourcesTable is the table that holds the database_sources relation/edge.
	DatabaseSourcesTable = "database_sources"
	// DatabaseSourcesInverseTable is the table name for the DatabaseSource entity.
	// It exists in this package in order to avoid circular dependency with the "databasesource" package.
	DatabaseSourcesInverseTable = "database_sources"
	// DatabaseSourcesColumn is the table column denoting the database_sources relation/edge.
	DatabaseSourcesColumn = "project_id"
	// DocumentsTable is the table that holds the documents relation/edge.
	DocumentsTable = "documents"
	// DocumentsInverseTable is the table name for the Document entity.
	// It exists in this package in order to avoid circular dependency with the "document" package.
	DocumentsInverseTable = "documents"
	// DocumentsColumn is the table column denoting the documents relation/edge.
	DocumentsColumn = "project_id"
	// ChunksTable is the table that holds the chunks relation/edge.
	ChunksTable = "document_chunks"
	// ChunksInverseTable is the table name for the DocumentChunk entity.
	// It exists in this package in order to avoid circular dependency with the "documentchunk" package.
	ChunksInverseTable = "document_chunks"
	// ChunksColumn is the table column denoting the chunks relation/edge.
	ChunksColumn = "project_id"
	// JobsTable is the table that holds the jobs relation/edge.
	JobsTable = "ingestion_jobs"
	// JobsInverseTable is the table name for the IngestionJob entity.
	// It exists in this package in order to avoid circular dependency with the "ingestionjob" package.
	JobsInverseTable = "ingestion_jobs"
	// JobsColumn is the table column denoting the jobs relation/edge.
	JobsColumn = "project_id"
	// AuditLogsTable is the table that holds the audit_logs relation/edge.
	AuditLogsTable = "audit_logs"
	// AuditLogsInverseTable is the table name for the AuditLog entity.
	// It exists in this package in order to avoid circular dependency with the "auditlog" package.
	AuditLogsInverseTable = "audit_logs"
	// AuditLogsColumn is the table column denoting the audit_logs relation/edge.
	AuditLogsColumn = "project_id"
)

// Columns holds all SQL columns for project fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldOwnerUserID,
	FieldEmbeddingProvider,
	FieldEmbeddingModel,
	FieldEmbeddingDimension,
	FieldLlmProvider,
	FieldLlmModel,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultEmbeddingProvider holds the default value on creation for the "embedding_provider" field.
	DefaultEmbeddingProvider string
	// DefaultEmbeddingModel holds the default value on creation for the "embedding_model" field.
	DefaultEmbeddingModel string
	// DefaultEmbeddingDimension holds the default value on creation for the "embedding_dimension" field.
	DefaultEmbeddingDimension int
	// DefaultLlmProvider holds the default value on creation for the "llm_provider" field.
	DefaultLlmProvider string
	// DefaultLlmModel holds the default value on creation for the "llm_model" field.
	DefaultLlmModel string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Project queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByEmbeddingProvider orders the results by the embedding_provider field.
func ByEmbeddingProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmbeddingProvider, opts...).ToFunc()
}

// ByEmbeddingModel orders the results by the embedding_model field.
func ByEmbeddingModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmbeddingModel, opts...).ToFunc()
}

// ByEmbeddingDimension orders the results by the embedding_dimension field.
func ByEmbeddingDimension(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmbeddingDimension, opts...).ToFunc()
}

// ByLlmProvider orders the results by the llm_provider field.
func ByLlmProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLlmProvider, opts...).ToFunc()
}

// ByLlmModel orders the results by the llm_model field.
func ByLlmModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLlmModel, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// BySourcesCount orders the results by sources count.
func BySourcesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSourcesStep(), opts...)
	}
}

// BySources orders the results by sources terms.
func BySources(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourcesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDatabaseSourcesCount orders the results by database_sources count.
func ByDatabaseSourcesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDatabaseSourcesStep(), opts...)
	}
}

// ByDatabaseSources orders the results by database_sources terms.
func ByDatabaseSources(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDatabaseSourcesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDocumentsCount orders the results by documents count.
func ByDocumentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDocumentsStep(), opts...)
	}
}

// ByDocuments orders the results by documents terms.
func ByDocuments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDocumentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChunksCount orders the results by chunks count.
func ByChunksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChunksStep(), opts...)
	}
}

// ByChunks orders the results by chunks terms.
func ByChunks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChunksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByJobsCount orders the results by jobs count.
func ByJobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJobsStep(), opts...)
	}
}

// ByJobs orders the results by jobs terms.
func ByJobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuditLogsCount orders the results by audit_logs count.
func ByAuditLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuditLogsStep(), opts...)
	}
}

// ByAuditLogs orders the results by audit_logs terms.
func ByAuditLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuditLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newSourcesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourcesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SourcesTable, SourcesColumn),
	)
}
func newDatabaseSourcesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DatabaseSourcesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DatabaseSourcesTable, DatabaseSourcesColumn),
	)
}
func newDocumentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DocumentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DocumentsTable, DocumentsColumn),
	)
}
func newChunksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChunksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChunksTable, ChunksColumn),
	)
}
func newJobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JobsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JobsTable, JobsColumn),
	)
}
func newAuditLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuditLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AuditLogsTable, AuditLogsColumn),
	)
}
