// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/your-org/contextforge/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// GithubID applies equality check predicate on the "github_id" field. It's identical to GithubIDEQ.
func GithubID(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGithubID, v))
}

// GithubLogin applies equality check predicate on the "github_login" field. It's identical to GithubLoginEQ.
func GithubLogin(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGithubLogin, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// EncryptedAccessToken applies equality check predicate on the "encrypted_access_token" field. It's identical to EncryptedAccessTokenEQ.
func EncryptedAccessToken(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEncryptedAccessToken, v))
}

// EncryptedRefreshToken applies equality check predicate on the "encrypted_refresh_token" field. It's identical to EncryptedRefreshTokenEQ.
func EncryptedRefreshToken(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEncryptedRefreshToken, v))
}

// TokenExpiresAt applies equality check predicate on the "token_expires_at" field. It's identical to TokenExpiresAtEQ.
func TokenExpiresAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// GithubIDEQ applies the EQ predicate on the "github_id" field.
func GithubIDEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGithubID, v))
}

// GithubIDNEQ applies the NEQ predicate on the "github_id" field.
func GithubIDNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldGithubID, v))
}

// GithubIDIn applies the In predicate on the "github_id" field.
func GithubIDIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldGithubID, vs...))
}

// GithubIDNotIn applies the NotIn predicate on the "github_id" field.
func GithubIDNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldGithubID, vs...))
}

// GithubIDGT applies the GT predicate on the "github_id" field.
func GithubIDGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldGithubID, v))
}

// GithubIDGTE applies the GTE predicate on the "github_id" field.
func GithubIDGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldGithubID, v))
}

// GithubIDLT applies the LT predicate on the "github_id" field.
func GithubIDLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldGithubID, v))
}

// GithubIDLTE applies the LTE predicate on the "github_id" field.
func GithubIDLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldGithubID, v))
}

// GithubIDIsNil applies the IsNil predicate on the "github_id" field.
func GithubIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldGithubID))
}

// GithubIDNotNil applies the NotNil predicate on the "github_id" field.
func GithubIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldGithubID))
}

// GithubLoginEQ applies the EQ predicate on the "github_login" field.
func GithubLoginEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGithubLogin, v))
}

// GithubLoginNEQ applies the NEQ predicate on the "github_login" field.
func GithubLoginNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldGithubLogin, v))
}

// GithubLoginIn applies the In predicate on the "github_login" field.
func GithubLoginIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldGithubLogin, vs...))
}

// GithubLoginNotIn applies the NotIn predicate on the "github_login" field.
func GithubLoginNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldGithubLogin, vs...))
}

// GithubLoginGT applies the GT predicate on the "github_login" field.
func GithubLoginGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldGithubLogin, v))
}

// GithubLoginGTE applies the GTE predicate on the "github_login" field.
func GithubLoginGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldGithubLogin, v))
}

// GithubLoginLT applies the LT predicate on the "github_login" field.
func GithubLoginLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldGithubLogin, v))
}

// GithubLoginLTE applies the LTE predicate on the "github_login" field.
func GithubLoginLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldGithubLogin, v))
}

// GithubLoginContains applies the Contains predicate on the "github_login" field.
func GithubLoginContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldGithubLogin, v))
}

// GithubLoginHasPrefix applies the HasPrefix predicate on the "github_login" field.
func GithubLoginHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldGithubLogin, v))
}

// GithubLoginHasSuffix applies the HasSuffix predicate on the "github_login" field.
func GithubLoginHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldGithubLogin, v))
}

// GithubLoginEqualFold applies the EqualFold predicate on the "github_login" field.
func GithubLoginEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldGithubLogin, v))
}

// GithubLoginContainsFold applies the ContainsFold predicate on the "github_login" field.
func GithubLoginContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldGithubLogin, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLIsNil applies the IsNil predicate on the "avatar_url" field.
func AvatarURLIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAvatarURL))
}

// AvatarURLNotNil applies the NotNil predicate on the "avatar_url" field.
func AvatarURLNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAvatarURL))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarURL, v))
}

// EncryptedAccessTokenEQ applies the EQ predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEncryptedAccessToken, v))
}

// EncryptedAccessTokenNEQ applies the NEQ predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEncryptedAccessToken, v))
}

// EncryptedAccessTokenIn applies the In predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEncryptedAccessToken, vs...))
}

// EncryptedAccessTokenNotIn applies the NotIn predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEncryptedAccessToken, vs...))
}

// EncryptedAccessTokenGT applies the GT predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEncryptedAccessToken, v))
}

// EncryptedAccessTokenGTE applies the GTE predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEncryptedAccessToken, v))
}

// EncryptedAccessTokenLT applies the LT predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEncryptedAccessToken, v))
}

// EncryptedAccessTokenLTE applies the LTE predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEncryptedAccessToken, v))
}

// EncryptedAccessTokenContains applies the Contains predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEncryptedAccessToken, v))
}

// EncryptedAccessTokenHasPrefix applies the HasPrefix predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEncryptedAccessToken, v))
}

// EncryptedAccessTokenHasSuffix applies the HasSuffix predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEncryptedAccessToken, v))
}

// EncryptedAccessTokenIsNil applies the IsNil predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEncryptedAccessToken))
}

// EncryptedAccessTokenNotNil applies the NotNil predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEncryptedAccessToken))
}

// EncryptedAccessTokenEqualFold applies the EqualFold predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEncryptedAccessToken, v))
}

// EncryptedAccessTokenContainsFold applies the ContainsFold predicate on the "encrypted_access_token" field.
func EncryptedAccessTokenContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEncryptedAccessToken, v))
}

// EncryptedRefreshTokenEQ applies the EQ predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEncryptedRefreshToken, v))
}

// EncryptedRefreshTokenNEQ applies the NEQ predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEncryptedRefreshToken, v))
}

// EncryptedRefreshTokenIn applies the In predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEncryptedRefreshToken, vs...))
}

// EncryptedRefreshTokenNotIn applies the NotIn predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEncryptedRefreshToken, vs...))
}

// EncryptedRefreshTokenGT applies the GT predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEncryptedRefreshToken, v))
}

// EncryptedRefreshTokenGTE applies the GTE predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEncryptedRefreshToken, v))
}

// EncryptedRefreshTokenLT applies the LT predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEncryptedRefreshToken, v))
}

// EncryptedRefreshTokenLTE applies the LTE predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEncryptedRefreshToken, v))
}

// EncryptedRefreshTokenContains applies the Contains predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEncryptedRefreshToken, v))
}

// EncryptedRefreshTokenHasPrefix applies the HasPrefix predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEncryptedRefreshToken, v))
}

// EncryptedRefreshTokenHasSuffix applies the HasSuffix predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEncryptedRefreshToken, v))
}

// EncryptedRefreshTokenIsNil applies the IsNil predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEncryptedRefreshToken))
}

// EncryptedRefreshTokenNotNil applies the NotNil predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEncryptedRefreshToken))
}

// EncryptedRefreshTokenEqualFold applies the EqualFold predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEncryptedRefreshToken, v))
}

// EncryptedRefreshTokenContainsFold applies the ContainsFold predicate on the "encrypted_refresh_token" field.
func EncryptedRefreshTokenContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEncryptedRefreshToken, v))
}

// TokenExpiresAtEQ applies the EQ predicate on the "token_expires_at" field.
func TokenExpiresAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtNEQ applies the NEQ predicate on the "token_expires_at" field.
func TokenExpiresAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIn applies the In predicate on the "token_expires_at" field.
func TokenExpiresAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtNotIn applies the NotIn predicate on the "token_expires_at" field.
func TokenExpiresAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtGT applies the GT predicate on the "token_expires_at" field.
func TokenExpiresAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtGTE applies the GTE predicate on the "token_expires_at" field.
func TokenExpiresAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLT applies the LT predicate on the "token_expires_at" field.
func TokenExpiresAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLTE applies the LTE predicate on the "token_expires_at" field.
func TokenExpiresAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIsNil applies the IsNil predicate on the "token_expires_at" field.
func TokenExpiresAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldTokenExpiresAt))
}

// TokenExpiresAtNotNil applies the NotNil predicate on the "token_expires_at" field.
func TokenExpiresAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldTokenExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProjects applies the HasEdge predicate on the "projects" edge.
func HasProjects() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProjectsTable, ProjectsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectsWith applies the HasEdge predicate on the "projects" edge with a given conditions (other predicates).
func HasProjectsWith(preds ...predicate.Project) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newProjectsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
